from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('api','0024_ai_assistant'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='PaymentTransaction',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(max_length=80)),('method',models.CharField(default='UPI',max_length=30)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('transaction_date',models.DateField()),('status',models.CharField(choices=[('Unmatched','Unmatched'),('Partial','Partial'),('Matched','Matched')],default='Unmatched',max_length=20)),('raw_payload',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payment_transactions',to='api.company')),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payment_transactions',to='api.customer')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'constraints':[models.UniqueConstraint(fields=('company','reference'),name='unique_company_payment_reference')]}),
        migrations.CreateModel(name='PaymentPromise',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('promised_amount',models.DecimalField(decimal_places=2,max_digits=14)),('promised_date',models.DateField()),('status',models.CharField(choices=[('Open','Open'),('Kept','Kept'),('Broken','Broken'),('Cancelled','Cancelled')],default='Open',max_length=20)),('notes',models.CharField(blank=True,max_length=240)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payment_promises',to='api.company')),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payment_promises',to='api.customer')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='CollectionTask',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('due_date',models.DateField()),('amount_due',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('priority',models.CharField(default='Normal',max_length=20)),('status',models.CharField(choices=[('Open','Open'),('Contacted','Contacted'),('Collected','Collected'),('Rescheduled','Rescheduled')],default='Open',max_length=20)),('notes',models.CharField(blank=True,max_length=240)),('created_at',models.DateTimeField(auto_now_add=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='collection_tasks',to=settings.AUTH_USER_MODEL)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='collection_tasks',to='api.company')),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='collection_tasks',to='api.customer'))]),
        migrations.CreateModel(name='PaymentAllocation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('created_at',models.DateTimeField(auto_now_add=True)),('invoice',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payment_allocations',to='api.invoice')),('transaction',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='allocations',to='api.paymenttransaction'))]),
    ]
