from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0025_collections_reconciliation'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='WarehouseBin',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=40)),('zone',models.CharField(blank=True,max_length=60)),('capacity',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('is_active',models.BooleanField(default=True)),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bins',to='api.warehouse'))],options={'constraints':[models.UniqueConstraint(fields=('warehouse','code'),name='unique_warehouse_bin_code')]}),
  migrations.CreateModel(name='BinStock',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('bin',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='stocks',to='api.warehousebin')),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bin_stocks',to='api.product'))],options={'constraints':[models.UniqueConstraint(fields=('bin','product'),name='unique_bin_product')]}),
  migrations.CreateModel(name='PickList',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('pick_no',models.CharField(max_length=40,unique=True)),('status',models.CharField(choices=[('Draft','Draft'),('Released','Released'),('Picking','Picking'),('Complete','Complete')],default='Draft',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='pick_lists',to=settings.AUTH_USER_MODEL)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='pick_lists',to='api.company')),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='pick_lists',to='api.warehouse'))]),
  migrations.CreateModel(name='PickListItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('requested_qty',models.DecimalField(decimal_places=2,max_digits=12)),('picked_qty',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('order',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='pick_items',to='api.order')),('pick_list',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='api.picklist')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='pick_items',to='api.product')),('source_bin',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='pick_items',to='api.warehousebin'))]),
  migrations.CreateModel(name='CycleCount',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('expected_qty',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('counted_qty',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('status',models.CharField(choices=[('Open','Open'),('Counted','Counted'),('Posted','Posted')],default='Open',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('bin',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='cycle_counts',to='api.warehousebin')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='cycle_counts',to='api.company')),('counted_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='cycle_counts',to='api.product')),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='cycle_counts',to='api.warehouse'))]),
 ]
