from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0028_automation_engine')]
 operations=[
  migrations.CreateModel(name='ExternalChannel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('provider',models.CharField(choices=[('WEBSITE','Website'),('ONDC','ONDC'),('MARKETPLACE','Marketplace'),('CUSTOM','Custom API')],default='WEBSITE',max_length=30)),('external_store_id',models.CharField(blank=True,max_length=120)),('is_active',models.BooleanField(default=True)),('settings',models.JSONField(blank=True,default=dict)),('last_sync_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='external_channels',to='api.company'))]),
  migrations.CreateModel(name='ExternalOrder',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('external_id',models.CharField(max_length=120)),('customer_name',models.CharField(max_length=160)),('customer_phone',models.CharField(blank=True,max_length=20)),('ship_to',models.JSONField(blank=True,default=dict)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('status',models.CharField(choices=[('New','New'),('Review','Review'),('Converted','Converted'),('Rejected','Rejected')],default='New',max_length=20)),('raw_payload',models.JSONField(blank=True,default=dict)),('received_at',models.DateTimeField(auto_now_add=True)),('channel',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='orders',to='api.externalchannel')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='external_orders',to='api.company')),('converted_order',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='external_sources',to='api.order'))],options={'constraints':[models.UniqueConstraint(fields=('channel','external_id'),name='unique_channel_external_order')]}),
  migrations.CreateModel(name='ExternalOrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('external_sku',models.CharField(max_length=80)),('name',models.CharField(max_length=180)),('quantity',models.DecimalField(decimal_places=2,max_digits=12)),('unit_price',models.DecimalField(decimal_places=2,max_digits=12)),('external_order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='api.externalorder')),('product',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='external_order_items',to='api.product'))]),
 ]
