from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0029_external_channels')]
 operations=[
  migrations.CreateModel(name='DistributionNetwork',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('code',models.CharField(max_length=40,unique=True)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('owner_company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='owned_distribution_networks',to='api.company'))]),
  migrations.CreateModel(name='NetworkMember',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('region',models.CharField(blank=True,max_length=100)),('territory',models.CharField(blank=True,max_length=100)),('share_inventory',models.BooleanField(default=True)),('share_secondary_sales',models.BooleanField(default=True)),('is_active',models.BooleanField(default=True)),('joined_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='network_memberships',to='api.company')),('network',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='members',to='api.distributionnetwork'))],options={'constraints':[models.UniqueConstraint(fields=('network','company'),name='unique_network_company_member')]}),
  migrations.CreateModel(name='NetworkSnapshot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('snapshot_date',models.DateField()),('inventory_value',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('stock_units',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('secondary_sales',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('open_orders',models.PositiveIntegerField(default=0)),('product_summary',models.JSONField(blank=True,default=list)),('created_at',models.DateTimeField(auto_now_add=True)),('member',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='snapshots',to='api.networkmember')),('network',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='snapshots',to='api.distributionnetwork'))],options={'constraints':[models.UniqueConstraint(fields=('network','member','snapshot_date'),name='unique_network_member_snapshot')]}),
 ]
