from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0030_distribution_network'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='PaymentLink',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('token',models.CharField(max_length=80,unique=True)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('status',models.CharField(default='Active',max_length=20)),('expires_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payment_links',to='api.company')),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payment_links',to='api.customer')),('invoice',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='payment_links',to='api.invoice'))]),
  migrations.CreateModel(name='CollectionReminder',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('channel',models.CharField(default='WhatsApp',max_length=20)),('scheduled_for',models.DateTimeField()),('status',models.CharField(default='Scheduled',max_length=20)),('message',models.CharField(max_length=500)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='collection_reminders',to='api.company')),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='collection_reminders',to='api.customer')),('invoice',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='collection_reminders',to='api.invoice'))]),
  migrations.CreateModel(name='ReceivableFinanceExport',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('export_no',models.CharField(max_length=40,unique=True)),('provider',models.CharField(default='TReDS-ready CSV',max_length=40)),('invoice_count',models.PositiveIntegerField(default=0)),('total_amount',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('payload',models.JSONField(blank=True,default=list)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='receivable_finance_exports',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
 ]
