from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies=[('api','0031_collection_assets'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='PickWave',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('wave_no',models.CharField(max_length=40,unique=True)),('status',models.CharField(choices=[('Planned','Planned'),('Released','Released'),('In Progress','In Progress'),('Complete','Complete')],default='Planned',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='pick_waves',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='pick_waves',to='api.warehouse')),('pick_lists',models.ManyToManyField(blank=True,related_name='waves',to='api.picklist'))]),
        migrations.CreateModel(name='PackingSlip',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('package_no',models.CharField(max_length=50,unique=True)),('carton_count',models.PositiveIntegerField(default=1)),('weight_kg',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('status',models.CharField(choices=[('Open','Open'),('Packed','Packed'),('Labelled','Labelled'),('Dispatched','Dispatched')],default='Open',max_length=20)),('packed_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='packing_slips',to='api.company')),('order',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='packing_slips',to='api.order')),('packed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('pick_list',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='packing_slips',to='api.picklist')),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='packing_slips',to='api.warehouse'))]),
    ]
