from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies=[('api','0032_wms_wave_packing'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='CRMLead',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('lead_no',models.CharField(max_length=40,unique=True)),('name',models.CharField(max_length=160)),('business_name',models.CharField(blank=True,max_length=180)),('phone',models.CharField(blank=True,max_length=20)),('email',models.EmailField(blank=True,max_length=254)),('source',models.CharField(default='Referral',max_length=80)),('territory',models.CharField(blank=True,max_length=100)),('status',models.CharField(choices=[('New','New'),('Qualified','Qualified'),('Meeting','Meeting'),('Quoted','Quoted'),('Negotiation','Negotiation'),('Won','Won'),('Lost','Lost')],default='New',max_length=20)),('estimated_value',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('expected_close',models.DateField(blank=True,null=True)),('lost_reason',models.CharField(blank=True,max_length=240)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='crm_leads',to='api.company')),('converted_customer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='source_leads',to='api.customer')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='crm_leads',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='CRMActivity',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('activity_type',models.CharField(default='Call',max_length=40)),('note',models.CharField(max_length=300)),('next_follow_up',models.DateTimeField(blank=True,null=True)),('completed',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='crm_activities',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('lead',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='activities',to='api.crmlead'))]),
    ]
