from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0036_smart_procurement'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='FleetVehicle',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('vehicle_no',models.CharField(max_length=30)),('vehicle_type',models.CharField(default='LCV',max_length=60)),('capacity_kg',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('driver_name',models.CharField(blank=True,max_length=120)),('driver_phone',models.CharField(blank=True,max_length=20)),('cost_per_km',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('is_active',models.BooleanField(default=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='fleet_vehicles',to='api.company'))],options={'constraints':[models.UniqueConstraint(fields=('company','vehicle_no'),name='unique_company_fleet_vehicle')]}),
  migrations.CreateModel(name='RoutePlan',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('route_no',models.CharField(max_length=40,unique=True)),('route_date',models.DateField()),('status',models.CharField(choices=[('Planned','Planned'),('Released','Released'),('Running','Running'),('Complete','Complete')],default='Planned',max_length=20)),('estimated_km',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('estimated_cost',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('optimization_score',models.DecimalField(decimal_places=2,default=0,max_digits=5)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='route_plans',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('vehicle',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='routes',to='api.fleetvehicle')),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='route_plans',to='api.warehouse'))]),
  migrations.CreateModel(name='RoutePlanStop',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('sequence',models.PositiveIntegerField(default=1)),('area',models.CharField(blank=True,max_length=120)),('delivery_window',models.CharField(blank=True,max_length=60)),('estimated_km_from_previous',models.DecimalField(decimal_places=2,default=0,max_digits=9)),('estimated_minutes',models.PositiveIntegerField(default=0)),('priority',models.PositiveSmallIntegerField(default=3)),('order',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='route_plan_stops',to='api.order')),('route',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='stops',to='api.routeplan'))],options={'ordering':['sequence']})]
