from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0038_credit_scoring_finance'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='UserMFASetting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('method',models.CharField(default='TOTP',max_length=20)),('secret_hash',models.CharField(blank=True,max_length=128)),('is_enabled',models.BooleanField(default=False)),('recovery_codes_hash',models.JSONField(blank=True,default=list)),('enabled_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='mfa_settings',to='api.company')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='mfa_setting',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='TrustedDevice',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('device_id',models.CharField(max_length=100)),('device_name',models.CharField(blank=True,max_length=160)),('fingerprint_hash',models.CharField(blank=True,max_length=128)),('last_ip',models.GenericIPAddressField(blank=True,null=True)),('trusted',models.BooleanField(default=False)),('last_seen_at',models.DateTimeField(auto_now=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='trusted_devices',to='api.company')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='trusted_devices',to=settings.AUTH_USER_MODEL))],options={'constraints':[models.UniqueConstraint(fields=('company','user','device_id'),name='unique_company_user_device')]}),
  migrations.CreateModel(name='SecurityEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event_type',models.CharField(max_length=80)),('severity',models.CharField(default='Info',max_length=20)),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('device_id',models.CharField(blank=True,max_length=100)),('detail',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='security_events',to='api.company')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='security_events',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='PrivacyRequest',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('request_no',models.CharField(max_length=40,unique=True)),('subject_name',models.CharField(max_length=160)),('subject_email',models.EmailField(blank=True,max_length=254)),('request_type',models.CharField(choices=[('Access','Access'),('Export','Export'),('Correct','Correct'),('Delete','Delete'),('Withdraw Consent','Withdraw Consent')],max_length=30)),('status',models.CharField(choices=[('Open','Open'),('Verifying','Verifying'),('Processing','Processing'),('Complete','Complete'),('Rejected','Rejected')],default='Open',max_length=20)),('due_date',models.DateField(blank=True,null=True)),('note',models.CharField(blank=True,max_length=300)),('created_at',models.DateTimeField(auto_now_add=True)),('completed_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='privacy_requests',to='api.company'))]),
  migrations.CreateModel(name='ConsentRecord',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('subject_key',models.CharField(max_length=160)),('purpose',models.CharField(max_length=180)),('granted',models.BooleanField(default=True)),('source',models.CharField(default='Portal',max_length=80)),('captured_at',models.DateTimeField(auto_now_add=True)),('withdrawn_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='consent_records',to='api.company'))])]
