from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0039_enterprise_security_privacy'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='IntegrationConnector',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('provider',models.CharField(max_length=60)),('name',models.CharField(max_length=120)),('status',models.CharField(default='Disconnected',max_length=30)),('config',models.JSONField(blank=True,default=dict)),('last_sync_at',models.DateTimeField(blank=True,null=True)),('last_error',models.CharField(blank=True,max_length=300)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='integration_connectors',to='api.company'))],options={'constraints':[models.UniqueConstraint(fields=('company','provider','name'),name='unique_company_integration_connector')]}),
  migrations.CreateModel(name='DeveloperApiKey',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('key_prefix',models.CharField(max_length=16)),('key_hash',models.CharField(max_length=128,unique=True)),('scopes',models.JSONField(blank=True,default=list)),('last_used_at',models.DateTimeField(blank=True,null=True)),('revoked_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='developer_api_keys',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='WebhookSubscription',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event',models.CharField(max_length=100)),('target_url',models.URLField()),('signing_secret_hash',models.CharField(max_length=128)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='webhook_subscriptions',to='api.company'))]),
  migrations.CreateModel(name='IntegrationDelivery',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event',models.CharField(max_length=100)),('status',models.CharField(default='Queued',max_length=30)),('attempt_count',models.PositiveIntegerField(default=0)),('payload',models.JSONField(blank=True,default=dict)),('last_error',models.CharField(blank=True,max_length=300)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='integration_deliveries',to='api.company')),('connector',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='deliveries',to='api.integrationconnector')),('webhook',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='deliveries',to='api.webhooksubscription'))])]
