from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies=[('api','0043_product_master_pim'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='InventoryLot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('lot_no',models.CharField(max_length=80)),('batch_no',models.CharField(blank=True,max_length=80)),('manufactured_on',models.DateField(blank=True,null=True)),('expiry_date',models.DateField(blank=True,null=True)),('received_qty',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('available_qty',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('unit_cost',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('status',models.CharField(choices=[('Available','Available'),('Quarantine','Quarantine'),('Expired','Expired'),('Recall','Recall'),('Closed','Closed')],default='Available',max_length=20)),('received_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='inventory_lots',to='api.company')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='inventory_lots',to='api.product')),('supplier',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='supplied_lots',to='api.supplier')),('warehouse',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='inventory_lots',to='api.warehouse'))],options={'constraints':[models.UniqueConstraint(fields=('company','product','lot_no'),name='unique_company_product_lot')]}),
      migrations.CreateModel(name='SerialUnit',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('serial_no',models.CharField(max_length=120)),('status',models.CharField(default='In Stock',max_length=30)),('warranty_until',models.DateField(blank=True,null=True)),('sold_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='serial_units',to='api.company')),('customer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='serial_units',to='api.customer')),('lot',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='serial_units',to='api.inventorylot')),('order',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='serial_units',to='api.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='serial_units',to='api.product')),('warehouse',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='serial_units',to='api.warehouse'))],options={'constraints':[models.UniqueConstraint(fields=('company','serial_no'),name='unique_company_serial_no')]}),
      migrations.CreateModel(name='TraceabilityEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event_type',models.CharField(max_length=50)),('reference',models.CharField(blank=True,max_length=120)),('quantity',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='traceability_events',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('lot',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='events',to='api.inventorylot')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='traceability_events',to='api.product')),('serial',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='events',to='api.serialunit'))])]
