from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0045_treasury_reconciliation_cashflow'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='RateAgreement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('agreement_no',models.CharField(max_length=50)),('title',models.CharField(max_length=180)),('start_date',models.DateField()),('end_date',models.DateField()),('status',models.CharField(default='Active',max_length=30)),('minimum_monthly_purchase',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('credit_days',models.PositiveSmallIntegerField(default=30)),('notes',models.TextField(blank=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='rate_agreements',to='api.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='rate_agreements',to='api.customer'))],options={'constraints':[models.UniqueConstraint(fields=('company','agreement_no'),name='unique_company_rate_agreement_no')]}),
  migrations.CreateModel(name='Tender',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('tender_no',models.CharField(max_length=60)),('title',models.CharField(max_length=200)),('due_date',models.DateField()),('expected_value',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('status',models.CharField(default='Draft',max_length=30)),('terms',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tenders',to='api.company')),('customer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='tenders',to='api.customer'))],options={'constraints':[models.UniqueConstraint(fields=('company','tender_no'),name='unique_company_tender_no')]}),
  migrations.CreateModel(name='RateAgreementItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('rate',models.DecimalField(decimal_places=2,max_digits=14)),('minimum_qty',models.DecimalField(decimal_places=2,default=1,max_digits=12)),('maximum_qty',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('escalation_percent',models.DecimalField(decimal_places=2,default=0,max_digits=7)),('agreement',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='api.rateagreement')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='contract_rates',to='api.product'))],options={'constraints':[models.UniqueConstraint(fields=('agreement','product'),name='unique_agreement_product_rate')]})]
