from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0049_warranty_rma_service'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='ExpenseClaim',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('claim_no',models.CharField(max_length=60)),('category',models.CharField(max_length=80)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('expense_date',models.DateField()),('payment_method',models.CharField(default='Cash',max_length=30)),('description',models.CharField(blank=True,max_length=300)),('receipt_url',models.URLField(blank=True)),('status',models.CharField(default='Submitted',max_length=30)),('approved_at',models.DateTimeField(blank=True,null=True)),('paid_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='approved_expense_claims',to=settings.AUTH_USER_MODEL)),('branch',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='expense_claims',to='api.branch')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='expense_claims',to='api.company')),('employee',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='expense_claims',to=settings.AUTH_USER_MODEL))],options={'constraints':[models.UniqueConstraint(fields=('company','claim_no'),name='unique_company_expense_claim_no')]}),
  migrations.CreateModel(name='PettyCashAccount',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('balance',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('branch',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='petty_cash_accounts',to='api.branch')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='petty_cash_accounts',to='api.company'))],options={'constraints':[models.UniqueConstraint(fields=('company','name'),name='unique_company_petty_cash_name')]}),
  migrations.CreateModel(name='PettyCashTransaction',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('transaction_date',models.DateField()),('transaction_type',models.CharField(default='Debit',max_length=20)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('note',models.CharField(blank=True,max_length=240)),('created_at',models.DateTimeField(auto_now_add=True)),('account',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='transactions',to='api.pettycashaccount')),('claim',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='petty_cash_transactions',to='api.expenseclaim')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))])]
