from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0050_expenses_petty_cash'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='ReportDefinition',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('data_source',models.CharField(max_length=80)),('dimensions',models.JSONField(blank=True,default=list)),('measures',models.JSONField(blank=True,default=list)),('filters',models.JSONField(blank=True,default=dict)),('group_by',models.JSONField(blank=True,default=list)),('is_shared',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='report_definitions',to='api.company')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='report_definitions',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='ScheduledReport',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('frequency',models.CharField(default='Weekly',max_length=30)),('delivery_time',models.TimeField(blank=True,null=True)),('weekdays',models.JSONField(blank=True,default=list)),('recipients',models.JSONField(blank=True,default=list)),('output_format',models.CharField(default='XLSX',max_length=20)),('is_active',models.BooleanField(default=True)),('last_run_at',models.DateTimeField(blank=True,null=True)),('next_run_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='scheduled_reports',to='api.company')),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='schedules',to='api.reportdefinition'))]),
  migrations.CreateModel(name='ReportRun',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(default='Queued',max_length=30)),('row_count',models.PositiveIntegerField(default=0)),('output_url',models.URLField(blank=True)),('error',models.CharField(blank=True,max_length=300)),('started_at',models.DateTimeField(blank=True,null=True)),('finished_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='runs',to='api.reportdefinition')),('schedule',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='runs',to='api.scheduledreport'))])]
