from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('api','0051_custom_reports')]
 operations=[
  migrations.CreateModel(name='ServiceHealth',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('service_name',models.CharField(max_length=100)),('category',models.CharField(default='Internal',max_length=60)),('status',models.CharField(default='Healthy',max_length=30)),('latency_ms',models.PositiveIntegerField(default=0)),('message',models.CharField(blank=True,max_length=300)),('checked_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='service_health_rows',to='api.company'))],options={'constraints':[models.UniqueConstraint(fields=('company','service_name'),name='unique_company_service_health')]}),
  migrations.CreateModel(name='BackgroundJob',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('job_type',models.CharField(max_length=100)),('job_key',models.CharField(max_length=120)),('status',models.CharField(default='Queued',max_length=30)),('attempts',models.PositiveIntegerField(default=0)),('payload',models.JSONField(blank=True,default=dict)),('last_error',models.CharField(blank=True,max_length=300)),('scheduled_at',models.DateTimeField(blank=True,null=True)),('started_at',models.DateTimeField(blank=True,null=True)),('finished_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='background_jobs',to='api.company'))],options={'constraints':[models.UniqueConstraint(fields=('company','job_key'),name='unique_company_background_job_key')]}),
  migrations.CreateModel(name='WebhookReplay',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('source',models.CharField(max_length=80)),('event_id',models.CharField(max_length=120)),('status',models.CharField(default='Failed',max_length=30)),('attempts',models.PositiveIntegerField(default=0)),('payload',models.JSONField(blank=True,default=dict)),('last_error',models.CharField(blank=True,max_length=300)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='webhook_replays',to='api.company'))]),
  migrations.CreateModel(name='AlertPolicy',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('condition',models.CharField(max_length=100)),('threshold',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('channels',models.JSONField(blank=True,default=list)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='alert_policies',to='api.company'))])]
