# Generated by Django 5.2.11 on 2026-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_company_whatsapp_phone_number_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrun",
            name="eta_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryrun",
            name="last_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryrun",
            name="last_location_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryrun",
            name="last_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryrun",
            name="tracking_token",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="deliverystop",
            name="delivery_otp",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="deliverystop",
            name="eta_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
