import { useEffect, useState } from 'react';
import { getApiResource, postApiAction } from '../services/api';
import { permissions } from '../data/demoData';
import { useAuth } from '../context/AuthContext';

const labels = { dashboard: 'Overview', products: 'Products', inventory: 'Inventory', customers: 'Customers', orders: 'Orders', invoices: 'GST invoices', purchases: 'Purchases', ledger: 'Credit ledger', payments: 'Payments', reports: 'Reports', team: 'Team', settings: 'Settings', approvals: 'Approvals', delivery: 'Delivery', assistant: 'AI Assistant', 'client-workflow': 'Order-to-cash', onboarding: 'Client onboarding' };

export default function AccessReviewPage() {
  const { mode, user } = useAuth(); const [data, setData] = useState({ role: user.role, allowedModules: permissions[user.role] || [], restrictedModules: [] }); const [notice, setNotice] = useState('');
  useEffect(() => { if (mode === 'api') getApiResource('access-review').then(setData).catch((err) => setNotice(err.message)); }, [mode]);
  const allowed = data.allowedModules || []; const restricted = data.restrictedModules || [];
  const check = async (module) => { if (mode !== 'api') return setNotice(`${labels[module] || module} is ${allowed.includes(module) ? 'allowed' : 'restricted'} for ${data.role}.`); try { const result = await postApiAction('access-review/', { module, action: 'view' }); setNotice(`${labels[module] || module}: ${result.allowed ? 'allowed' : 'blocked'} for ${result.role}.`); } catch (err) { setNotice(err.message); } };
  return <div className="access-review-page"><div className="module-header"><div><span className="section-kicker">Role governance</span><h1>Workspace access review</h1><p>Validate the same role boundary in the sidebar and in the Django API before a client goes live.</p></div><span className="feature-badge">{data.role}</span></div>{notice && <div className="inline-notice">{notice}</div>}<div className="module-summary"><div><span>Current role</span><strong>{data.role}</strong><small>{data.policy?.[data.role] || 'Tenant-scoped access'}</small></div><div><span>Allowed modules</span><strong>{allowed.length}</strong><small>visible workspace capabilities</small></div><div><span>Restricted modules</span><strong>{restricted.length}</strong><small>blocked by role policy</small></div></div><div className="access-grid"><article className="panel module-panel"><div className="panel-head"><div><span>Allowed</span><h3>What this person can open</h3></div></div><div className="access-list">{allowed.map((module) => <button key={module} onClick={() => check(module)}><span>✓</span>{labels[module] || module}<small>Verify API</small></button>)}</div></article><article className="panel module-panel"><div className="panel-head"><div><span>Restricted</span><h3>What stays protected</h3></div></div><div className="access-list restricted">{restricted.slice(0, 30).map((module) => <button key={module} onClick={() => check(module)}><span>–</span>{labels[module] || module}<small>Check boundary</small></button>)}</div></article></div></div>;
}
