import { useEffect, useMemo, useState } from 'react';
const API=(import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api').replace(/\/$/,'');
const demoProducts=[{id:1,sku:'AN-MCB-32',name:'Anchor 32A DP MCB',stock:24,unit:'pcs',price:465,gst:18},{id:2,sku:'HA-LED-12',name:'Havells 12W LED Bulb',stock:86,unit:'pcs',price:132,gst:18},{id:3,sku:'PC-25-RD',name:'Polycab 2.5mm Wire Red',stock:7,unit:'coil',price:1940,gst:18}];
export default function CustomerPortalPage({navigate}){const[token,setToken]=useState(localStorage.getItem('setustock_portal_token')||'');const[customer,setCustomer]=useState(()=>JSON.parse(localStorage.getItem('setustock_portal_customer')||'null'));const[data,setData]=useState({products:demoProducts,credit:{outstanding:58240,limit:150000},orders:[]});const[cart,setCart]=useState([]);const[notice,setNotice]=useState('');const demo=String(import.meta.env.VITE_APP_MODE||'demo')==='demo';
useEffect(()=>{if(!token)return;fetch(`${API}/portal/catalog/`,{headers:{Authorization:`Portal ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>{if(!demo){setToken('');localStorage.removeItem('setustock_portal_token')}})},[token]);
const total=useMemo(()=>cart.reduce((n,x)=>n+x.price*x.quantity,0),[cart]);
const login=async(e)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget).entries());if(demo&&f.email==='dealer@setustock.demo'&&f.pin==='1234'){const c={name:'R.K. Trading Co.'};setCustomer(c);setToken('demo');localStorage.setItem('setustock_portal_customer',JSON.stringify(c));localStorage.setItem('setustock_portal_token','demo');return;}try{const r=await fetch(`${API}/portal/login/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const j=await r.json();if(!r.ok)throw new Error(j.detail);setToken(j.token);setCustomer(j.customer);localStorage.setItem('setustock_portal_token',j.token);localStorage.setItem('setustock_portal_customer',JSON.stringify(j.customer));}catch(err){setNotice(err.message||'Login failed')}};
const add=p=>setCart(c=>{const hit=c.find(x=>x.id===p.id);return hit?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1}]});
const place=async()=>{if(!cart.length)return; if(token==='demo'){setNotice(`Demo order WEB-DEMO-${Date.now().toString().slice(-5)} submitted.`);setCart([]);return;}try{const r=await fetch(`${API}/portal/orders/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Portal ${token}`},body:JSON.stringify({items:cart.map(x=>({productId:x.id,quantity:x.quantity}))})});const j=await r.json();if(!r.ok)throw new Error(j.detail);setNotice(`Order request ${j.requestNo} submitted.`);setCart([]);}catch(err){setNotice(err.message)}};
if(!token)return <div className="portal-shell"><header><button onClick={()=>navigate('/')}>← SetuStock</button><span>Dealer Portal</span></header><main className="portal-login"><section><span className="eyebrow">B2B ordering</span><h1>Order stock without calling the counter.</h1><p>See your dealer pricing, available stock, credit position and repeat orders from one clean portal.</p></section><form onSubmit={login}><h2>Customer login</h2>{notice&&<div className="inline-notice">{notice}</div>}<label>Email<input name="email" type="email" defaultValue="dealer@setustock.demo" required/></label><label>4-digit PIN<input name="pin" type="password" defaultValue="1234" required/></label><button>Open portal</button><small>Demo: dealer@setustock.demo / 1234</small></form></main></div>;
return <div className="portal-shell"><header><button onClick={()=>navigate('/')}>SetuStock</button><span>{customer?.name||'Dealer account'}</span><button onClick={()=>{localStorage.removeItem('setustock_portal_token');setToken('')}}>Sign out</button></header><main className="portal-body">{notice&&<div className="inline-notice">{notice}</div>}<section className="portal-hero"><div><span className="eyebrow">Dealer workspace</span><h1>Good afternoon, {customer?.name||'partner'}.</h1><p>Your negotiated prices are already applied.</p></div><div className="credit-card"><small>Outstanding / limit</small><strong>₹{Number(data.credit.outstanding).toLocaleString('en-IN')} / ₹{Number(data.credit.limit).toLocaleString('en-IN')}</strong><i style={{width:`${Math.min(100,(data.credit.outstanding/data.credit.limit)*100)}%`}}/></div></section><div className="portal-grid"><section><div className="portal-title"><h2>Live catalogue</h2><span>{data.products.length} products</span></div><div className="portal-products">{data.products.map(p=><article key={p.id}><div className="sku">{p.sku}</div><h3>{p.name}</h3><p>{p.stock} {p.unit} available · GST {p.gst}%</p><footer><strong>₹{Number(p.price).toLocaleString('en-IN')}</strong><button onClick={()=>add(p)}>Add</button></footer></article>)}</div></section><aside className="portal-cart"><h2>Current order</h2>{!cart.length&&<p className="muted">Your cart is empty.</p>}{cart.map(x=><div key={x.id}><span>{x.name}<small>{x.quantity} × ₹{x.price}</small></span><strong>₹{(x.price*x.quantity).toLocaleString('en-IN')}</strong></div>)}<footer><span>Estimated total</span><strong>₹{total.toLocaleString('en-IN')}</strong></footer><button disabled={!cart.length} onClick={place}>Submit B2B order</button></aside></div></main></div>}
