import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { createApiResource, getApiResource } from '../services/api';

const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;
const demo = { summary: { customers: 126, overdue: 18, scheduled: 24, activeCampaigns: 4, consented: 88 }, customers: [{ id: 1, name: 'Metro Electricals', phone: '9811000000', segment: 'Overdue', outstanding: 38400, creditLimit: 150000, consented: true }, { id: 2, name: 'R.K. Trading Co.', phone: '9811000001', segment: 'Active', outstanding: 0, creditLimit: 120000, consented: true }, { id: 3, name: 'NCR Buildmart', phone: '9811000002', segment: 'At risk', outstanding: 0, creditLimit: 95000, consented: false }], campaigns: [{ id: 1, name: 'Overdue payment reminder', event: 'invoice.overdue', conditions: { days: 7 }, actions: [{ type: 'schedule_reminder', channel: 'WhatsApp' }], active: true }], reminders: [{ id: 1, customer: 'Metro Electricals', channel: 'WhatsApp', scheduledFor: '2026-09-29T10:00:00Z', status: 'Scheduled', message: 'Payment reminder for Metro Electricals' }] };

export default function CustomerEngagementPage() {
  const { mode } = useAuth(); const [data, setData] = useState(demo); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { if (mode !== 'api') { setData(demo); return; } try { setData(await getApiResource('customer-engagement')); } catch (error) { setNotice(error.message); } };
  useEffect(() => { load(); }, [mode]);
  const action = async (name, payload = {}) => { setBusy(true); try { if (mode === 'api') await createApiResource('customer-engagement', { action: name, ...payload }); setNotice(name === 'create-campaign' ? 'Campaign created and ready for the automation engine.' : name === 'consent' ? 'Customer communication consent recorded.' : 'Customer reminder scheduled.'); await load(); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const first = data.customers?.[0]; const summary = data.summary || demo.summary;
  return <div className="customer-engagement-page">
    {notice && <div className="inline-notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    <div className="module-header"><div><span className="eyebrow">Retention automation</span><h1>Customer engagement</h1><p>Turn customer segments into consent-aware reorder nudges, payment reminders and personalized follow-up tasks.</p></div><div className="engagement-actions"><button onClick={() => action('create-campaign', { name: 'Reorder nudge campaign', event: 'customer.reorder_due', channel: 'WhatsApp', message: 'Your regular stock may be due for replenishment. Reply with your quantity.' })} disabled={busy}>Create reorder campaign</button>{first && <button className="secondary-btn" onClick={() => action('schedule-reminder', { customerId: first.id, channel: 'WhatsApp', message: `Hello ${first.name}, your SetuStock account has a follow-up reminder.` })} disabled={busy}>Schedule follow-up</button>}</div></div>
    <div className="engagement-summary"><article><span>Customers</span><strong>{summary.customers}</strong><small>active accounts</small></article><article><span>Overdue</span><strong>{summary.overdue}</strong><small>collection opportunity</small></article><article><span>Scheduled</span><strong>{summary.scheduled}</strong><small>outbound reminders</small></article><article><span>Consent coverage</span><strong>{summary.customers ? Math.round(summary.consented / summary.customers * 100) : 0}%</strong><small>{summary.consented} customers opted in</small></article></div>
    <div className="engagement-grid"><article className="panel module-panel"><div className="panel-head"><div><span>Audience intelligence</span><h3>Customer segments</h3></div></div><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Customer</th><th>Segment</th><th>Outstanding</th><th>Credit limit</th><th>Consent</th><th>Action</th></tr></thead><tbody>{(data.customers || []).map(row => <tr key={row.id}><td><strong>{row.name}</strong><small>{row.phone || 'No phone saved'}</small></td><td><span className={`segment-badge segment-${row.segment.toLowerCase().replace(' ', '-')}`}>{row.segment}</span></td><td>{money(row.outstanding)}</td><td>{money(row.creditLimit)}</td><td>{row.consented ? 'Opted in' : 'Not recorded'}</td><td>{!row.consented ? <button className="table-action" onClick={() => action('consent', { customerId: row.id, granted: true })}>Record consent</button> : <button className="table-action" onClick={() => action('schedule-reminder', { customerId: row.id, channel: 'WhatsApp', message: `Follow-up for ${row.name}` })}>Schedule</button>}</td></tr>)}</tbody></table></div></article><article className="panel module-panel"><div className="panel-head"><div><span>Outbound queue</span><h3>Scheduled reminders</h3></div></div><div className="engagement-reminders">{(data.reminders || []).map(row => <div key={row.id}><span className="reminder-channel">{row.channel}</span><section><strong>{row.customer}</strong><small>{row.message}</small></section><time>{new Date(row.scheduledFor).toLocaleDateString('en-IN')}</time></div>)}</div></article></div>
    <article className="panel module-panel"><div className="panel-head"><div><span>Reusable playbooks</span><h3>Active campaigns</h3></div></div><div className="campaign-grid">{(data.campaigns || []).map(row => <div key={row.id}><strong>{row.name}</strong><small>{row.event} · {(row.actions || []).map(actionItem => actionItem.type || actionItem).join(', ')}</small><span>{row.active ? 'Active' : 'Paused'}</span></div>)}</div></article>
  </div>;
}
