import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { createApiResource, getApiResource } from '../services/api';

const demo = { summary: { securityScore: 82, mfaCoverage: 80, trustedDevices: 4, openPrivacyRequests: 1, criticalEvents: 0 }, continuity: { backupStatus: 'Healthy', lastRun: 'Today, 02:00', provider: 'Encrypted object storage', restoreDrill: 'Last month' }, controls: [{ name: 'MFA coverage', status: 'Needs attention', detail: '4 of 5 users protected' }, { name: 'Backup verification', status: 'Healthy', detail: 'Healthy · Today, 02:00' }, { name: 'Tenant export', status: 'Ready', detail: '842 audit records available' }, { name: 'Privacy queue', status: 'Needs attention', detail: '1 request open' }], devices: [{ id: 1, user: 'Arjun Khanna', name: 'Chrome on Windows', trusted: true, ip: '192.168.1.42', lastSeen: 'Today, 10:20' }], privacy: [{ id: 1, requestNo: 'PRIV-260921-01', subject: 'Demo data subject', type: 'Export', status: 'Open', due: '2026-10-10' }], events: [{ id: 1, type: 'MFA_ENABLED', severity: 'Info', user: 'Arjun Khanna', createdAt: '2026-09-28T09:00:00Z' }] };

export default function CyberTrustPage() {
  const { mode } = useAuth(); const [data, setData] = useState(demo); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { if (mode !== 'api') { setData(demo); return; } try { setData(await getApiResource('cyber-trust')); } catch (error) { setNotice(error.message); } };
  useEffect(() => { load(); }, [mode]);
  const action = async (name) => { setBusy(true); try { const result = mode === 'api' ? await createApiResource('cyber-trust', { action: name }) : { records: 842 }; setNotice(name === 'backup-check' ? 'Backup verification recorded.' : name === 'restore-drill' ? 'Restore drill completed in simulation mode.' : `Tenant export manifest prepared for ${result.records || 0} audit records.`); await load(); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const summary = data.summary || demo.summary;
  return <div className="cyber-trust-page">
    {notice && <div className="inline-notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    <div className="module-header"><div><span className="eyebrow">Business resilience</span><h1>Cyber trust center</h1><p>Prove that the workspace is protected, recoverable and ready for privacy or security review.</p></div><div className="trust-actions"><button onClick={() => action('backup-check')} disabled={busy}>Verify backup</button><button onClick={() => action('restore-drill')} disabled={busy}>Run restore drill</button><button onClick={() => action('export-tenant')} disabled={busy}>Prepare tenant export</button></div></div>
    <div className="trust-summary"><article><span>Security score</span><strong>{summary.securityScore}/100</strong><small>control readiness</small></article><article><span>MFA coverage</span><strong>{summary.mfaCoverage}%</strong><small>staff protection</small></article><article><span>Trusted devices</span><strong>{summary.trustedDevices}</strong><small>known sessions</small></article><article><span>Open privacy requests</span><strong>{summary.openPrivacyRequests}</strong><small>review queue</small></article></div>
    <div className="trust-grid"><article className="panel module-panel"><div className="panel-head"><div><span>Control posture</span><h3>Security controls</h3></div></div><div className="trust-control-list">{(data.controls || []).map(control => <div key={control.name}><span className={`control-dot ${control.status === 'Healthy' || control.status === 'Ready' ? 'healthy' : 'attention'}`} /><section><strong>{control.name}</strong><small>{control.detail}</small></section><b>{control.status}</b></div>)}</div></article><article className="panel module-panel"><div className="panel-head"><div><span>Recovery readiness</span><h3>Business continuity</h3></div></div><div className="continuity-card"><div><span>Backup status</span><strong>{data.continuity?.backupStatus}</strong><small>{data.continuity?.provider}</small></div><div><span>Last backup</span><strong>{data.continuity?.lastRun}</strong><small>verification is audited</small></div><div><span>Restore drill</span><strong>{data.continuity?.restoreDrill}</strong><small>run before major releases</small></div></div></article></div>
    <div className="trust-grid"><article className="panel module-panel"><div className="panel-head"><div><span>Identity surface</span><h3>Trusted devices</h3></div></div><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>User</th><th>Device</th><th>IP</th><th>Status</th><th>Last seen</th></tr></thead><tbody>{(data.devices || []).map(row => <tr key={row.id}><td>{row.user}</td><td>{row.name}</td><td>{row.ip || '—'}</td><td>{row.trusted ? 'Trusted' : 'Review'}</td><td>{row.lastSeen}</td></tr>)}</tbody></table></div></article><article className="panel module-panel"><div className="panel-head"><div><span>Evidence trail</span><h3>Recent security events</h3></div></div><div className="trust-events">{(data.events || []).slice(0, 6).map(row => <div key={row.id}><strong>{row.type}</strong><small>{row.user} · {new Date(row.createdAt).toLocaleString('en-IN')}</small><span>{row.severity}</span></div>)}</div></article></div>
  </div>;
}
