import { useState } from 'react';
import { commitImport, downloadCsv, previewImport, rollbackImport } from '../services/api';
import { useAuth } from '../context/AuthContext';

const resources = [
  ['products', 'Products', 'SKU, pricing, GST and reorder settings'], ['customers', 'Customers', 'Dealer accounts, GSTIN and credit limits'], ['suppliers', 'Suppliers', 'Supplier master and contact details'],
  ['opening-stock', 'Opening stock', 'Warehouse balances and reserved quantity'], ['ledger', 'Customer ledger', 'Invoice, payment and ageing history'], ['invoices', 'Invoices', 'Invoice headers linked to existing orders'],
];

export default function DataExchangePage() {
  const { mode, user } = useAuth(); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(''); const [preview, setPreview] = useState(null);
  const canImport = ['OWNER', 'MANAGER'].includes(user.role);
  const upload = async (resource, event) => { const file = event.target.files?.[0]; if (!file) return; setBusy(resource); try { if (mode !== 'api') setNotice('Demo mode: connect Django to preview client data.'); else { const result = await previewImport(resource, file); setPreview(result); setNotice(`${result.rows} ${resource} row(s) checked. Review validation results before committing.`); } } catch (err) { setNotice(err.message); } finally { setBusy(''); event.target.value = ''; } };
  const commit = async () => { if (!preview) return; setBusy('commit'); try { const result = await commitImport(preview.id); setPreview(result); setNotice(`Import committed: ${result.created} created, ${result.updated} updated.`); } catch (err) { setNotice(err.message); } finally { setBusy(''); } };
  const rollback = async () => { if (!preview) return; setBusy('rollback'); try { const result = await rollbackImport(preview.id); setPreview(result); setNotice('Import rolled back. The previous records were restored.'); } catch (err) { setNotice(err.message); } finally { setBusy(''); } };
  const exportIt = async (resource) => { try { if (mode !== 'api') return setNotice('Demo mode: exports are available with the live Django API.'); await downloadCsv(resource); setNotice(`${resource} export downloaded.`); } catch (err) { setNotice(err.message); } };
  return <div className="exchange-page"><div className="module-header"><div><span className="section-kicker">Client data operations</span><h1>Import & export center</h1><p>Move approved master data into SetuStock and give the client controlled, auditable exports for finance and operations.</p></div><span className="feature-badge">Preview before commit</span></div>{notice && <div className="inline-notice">{notice}</div>}{preview && <article className="panel import-review-card"><div className="panel-head"><div><span>Import review · {preview.filename}</span><h3>{preview.status === 'Completed' ? 'Import completed' : preview.status === 'Rolled back' ? 'Import rolled back' : 'Review validation results'}</h3></div><div className="row-actions">{preview.status === 'Ready' && <button onClick={commit} disabled={busy}>{busy === 'commit' ? 'Committing…' : 'Commit import'}</button>}{preview.status === 'Completed' && <button className="secondary-btn" onClick={rollback} disabled={busy}>{busy === 'rollback' ? 'Rolling back…' : 'Rollback import'}</button>}<button className="secondary-btn" onClick={() => setPreview(null)}>Close</button></div></div><div className="report-grid"><article><span>Rows</span><strong>{preview.rows}</strong><small>{preview.resource}</small></article><article><span>Validation errors</span><strong>{preview.errors}</strong><small>must be zero to commit</small></article><article><span>Duplicates</span><strong>{preview.duplicates}</strong><small>existing records detected</small></article></div>{(preview.validationErrors || []).slice(0, 5).map((row, index) => <div className="inline-notice" key={`${row.row}-${index}`}>Row {row.row}: {row.field} — {row.message}</div>)}</article>}<div className="exchange-grid">{resources.map(([resource, title, description]) => <article className="panel exchange-card" key={resource}><div><span>{resource === 'opening-stock' ? 'Inventory' : resource === 'ledger' || resource === 'invoices' ? 'Finance' : 'Master data'}</span><h3>{title}</h3><p>{description}</p></div><div className="row-actions"><button className="secondary-btn" onClick={() => exportIt(resource)}>Export CSV</button>{canImport && resource !== 'ledger' && <label className="secondary-btn csv-button">{busy === resource ? 'Checking…' : 'Preview CSV / XLSX'}<input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" hidden onChange={(event) => upload(resource, event)} /></label>}</div></article>)}</div><div className="exchange-note"><strong>Import rules</strong><span>Products, customers and suppliers upsert by their code. Opening stock matches SKU + warehouse code. Review duplicates and validation errors before commit; completed imports can be rolled back.</span></div></div>;
}
