import { useMemo, useState } from 'react';
import { permissions, roleHomeCopy } from '../data/demoData';
import { useAuth } from '../context/AuthContext';

const personas = [['OWNER', 'Owner', 'Full business visibility'], ['MANAGER', 'Manager', 'Operations and approvals'], ['SALES', 'Sales', 'Pipeline and collections'], ['WAREHOUSE', 'Warehouse', 'Stock and fulfilment'], ['ACCOUNTANT', 'Accountant', 'Invoices and ledgers']];
const steps = [['01', 'Start with the control room', 'Show dashboard metrics, attention alerts and current orders.'], ['02', 'Walk the golden path', 'Open Order-to-cash and explain enquiry → invoice → payment → e-POD.'], ['03', 'Switch the persona', 'Show how the same company becomes a focused workspace for each role.'], ['04', 'Prove client readiness', 'Open onboarding, access review, data exchange and support center.']];

export default function DemoPresentationPage() {
  const { user, mode, setUser } = useAuth(); const [active, setActive] = useState(0); const [notice, setNotice] = useState('');
  const current = useMemo(() => steps[active], [active]);
  const switchPersona = (role) => { if (mode !== 'demo') return setNotice('Persona switching is available only for safe demo sessions.'); const next = { ...user, role, permissions: permissions[role], name: role === 'OWNER' ? 'Arjun Khanna' : role === 'MANAGER' ? 'Meera Sethi' : role === 'SALES' ? 'Rohit Bansal' : role === 'WAREHOUSE' ? 'Imran Ali' : 'Nisha Gupta' }; localStorage.setItem('setustock_auth', JSON.stringify(next)); setUser(next); setNotice(`${role} persona loaded. Sidebar and workspace permissions updated.`); };
  const reset = () => { localStorage.removeItem('setustock_demo_scenario'); setActive(0); setNotice('Demo presentation reset to the opening scenario.'); };
  return <div className="demo-presentation-page"><div className="module-header"><div><span className="section-kicker">Client presentation mode</span><h1>Run a confident SetuStock demo</h1><p>Use this guided script to demonstrate the platform’s operating rhythm, role boundaries and go-live readiness without changing production data.</p></div><div className="row-actions"><button className="secondary-btn" onClick={reset}>Reset demo</button><button onClick={() => setActive((active + 1) % steps.length)}>Next step →</button></div></div>{notice && <div className="inline-notice">{notice}</div>}<section className="demo-now"><div><span>Now presenting</span><strong>{current[1]}</strong><p>{current[2]}</p></div><div className="demo-step-count"><strong>{current[0]}</strong><small>of 04</small></div></section><article className="panel module-panel demo-script"><div className="panel-head"><div><span>Guided storyline</span><h3>Four moments that land with a client</h3></div></div><div className="demo-step-grid">{steps.map(([number, title, description], index) => <button key={number} className={active === index ? 'active' : ''} onClick={() => setActive(index)}><span>{number}</span><strong>{title}</strong><small>{description}</small></button>)}</div></article><article className="panel module-panel demo-personas"><div className="panel-head"><div><span>Persona switcher</span><h3>Show the right window for every team member</h3></div></div><div className="persona-grid">{personas.map(([role, label, description]) => <button key={role} className={user.role === role ? 'active' : ''} onClick={() => switchPersona(role)}><span>{label.slice(0, 1)}</span><div><strong>{label}</strong><small>{description}</small></div></button>)}</div><p className="demo-safety">Current session: <strong>{mode === 'demo' ? 'Safe demo mode' : 'Live API mode'}</strong>. Persona switching never changes server-side users.</p></article></div>;
}
