import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { createApiResource, getApiResource } from '../services/api';
import { demoIntegrations } from '../data/strategicData';

const templates = [{ provider: 'TALLY', name: 'Tally Prime connector', description: 'Ledger, invoice and payment synchronisation' }, { provider: 'BUSY', name: 'BUSY accounting connector', description: 'GST invoice and customer ledger exchange' }, { provider: 'SAP', name: 'SAP Business One adapter', description: 'Orders, inventory and supplier documents' }, { provider: 'ZOHO', name: 'Zoho Books connector', description: 'Customer, invoice and payment synchronisation' }, { provider: 'QUICKBOOKS', name: 'QuickBooks Online connector', description: 'Accounting export and reconciliation feed' }];

export default function IntegrationMarketplacePage() {
  const { mode } = useAuth();
  const [data, setData] = useState({ ...demoIntegrations, marketplace: templates.map(t => ({ ...t, installed: false, status: 'Available' })), edi: { queued: 2, delivered: 14, documentTypes: ['purchase.order', 'advance.shipment', 'supplier.invoice'] }, sandbox: { available: true, basePath: '/api/public/v1/order-intake/', docsPath: '/docs/integrations' } });
  const [notice, setNotice] = useState('');
  const load = () => { if (mode === 'api') getApiResource('integrations').then(setData).catch(e => setNotice(e.message)); };
  useEffect(() => { load(); }, [mode]);
  const install = async (template) => { try { if (mode === 'api') await createApiResource('integrations', { action: 'install-template', provider: template.provider, name: template.name }); setNotice(`${template.name} installed. Add credentials before live sync.`); load(); } catch (e) { setNotice(e.message); } };
  const test = async (row) => { try { if (mode === 'api') await createApiResource('integrations', { action: 'test-connector', id: row.id }); setNotice(`${row.name} health check passed.`); load(); } catch (e) { setNotice(e.message); } };
  const queueEdi = async (event) => { try { if (mode === 'api') await createApiResource('integrations', { action: 'publish-edi', event, payload: { demo: true, source: 'SetuStock' } }); setNotice(`${event} document queued for the connected partner connector.`); load(); } catch (e) { setNotice(e.message); } };
  const connectors = data.connectors || [];
  return <div><div className="module-header"><div><span className="eyebrow">Composable operations</span><h1>Integration marketplace & EDI</h1><p>Connect the accounting and supplier tools your distributors already use, then exchange orders, invoices and fulfilment documents through one monitored boundary.</p></div><button onClick={() => mode === 'api' ? createApiResource('integrations', { action: 'sandbox' }).then(() => setNotice('Sandbox access is ready.')) : setNotice('Demo sandbox access is ready.')}>Open sandbox</button></div>{notice && <div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Connected</span><strong>{data.summary?.connected || 0}/{data.summary?.connectors || 0}</strong><small>connector health</small></article><article><span>EDI queued</span><strong>{data.edi?.queued || 0}</strong><small>partner documents</small></article><article><span>Delivered</span><strong>{data.edi?.delivered || 0}</strong><small>document events</small></article><article><span>Sandbox</span><strong>{data.sandbox?.available ? 'Ready' : 'Off'}</strong><small>{data.sandbox?.basePath}</small></article></div><article className="panel integration-marketplace"><div className="panel-head"><div><span>Prebuilt adapters</span><h3>Install the tools your team already trusts</h3></div></div><div className="integration-template-grid">{(data.marketplace || templates).map(t => <div className="integration-template" key={t.provider}><span className="integration-logo">{t.provider.slice(0, 2)}</span><div><strong>{t.name}</strong><small>{t.description}</small></div><button onClick={() => install(t)} disabled={t.installed}>{t.installed ? 'Installed' : 'Install'}</button></div>)}</div></article><article className="panel module-panel"><div className="panel-head"><div><span>Connector health</span><h3>Live integrations</h3></div></div><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Provider</th><th>Connector</th><th>Status</th><th>Last sync</th><th>Action</th></tr></thead><tbody>{connectors.map(row => <tr key={row.id}><td>{row.provider}</td><td><strong>{row.name}</strong><small>{row.lastError || 'No errors reported'}</small></td><td>{row.status}</td><td>{row.lastSync ? new Date(row.lastSync).toLocaleString() : 'Not synced'}</td><td><button className="table-action" onClick={() => test(row)}>Run health check</button></td></tr>)}</tbody></table></div></article><article className="panel module-panel"><div className="panel-head"><div><span>Supplier exchange</span><h3>Queue an EDI document</h3></div></div><div className="edi-actions">{(data.edi?.documentTypes || ['purchase.order', 'advance.shipment', 'supplier.invoice']).map(event => <button key={event} onClick={() => queueEdi(event)}>{event.replace('.', ' → ')}<small>Queue for connector</small></button>)}</div></article></div>;
}
