import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { getApiResource, createApiResource } from '../services/api';
import { demoNextgen } from '../data/nextgenData';
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
const configs={
 'product-master':{eyebrow:'Trusted master data',title:'Product Master / PIM',text:'Govern SKU, HSN, GST, barcode, UOM, pricing and traceability rules from one controlled master.',action:'refresh-quality',label:'Recalculate quality',stats:[['products','Products'],['qualityIssues','Quality issues'],['pendingChanges','Pending changes'],['governed','Approved']],table:'products',cols:[['sku','SKU'],['name','Product'],['brand','Brand'],['hsn','HSN'],['gst','GST %'],['uom','UOM'],['quality','Quality'],['status','Governance']]},
 traceability:{eyebrow:'Physical stock identity',title:'Batch / Serial / Expiry Traceability',text:'Trace lots, serials, expiry dates, recalls and warranty identity from receipt to customer.',action:'receive-lot',label:'Receive demo lot',stats:[['lots','Lots'],['serials','Serial units'],['expiring','Expiring'],['recalls','Recalls']],table:'lots',cols:[['product','Product'],['warehouse','Warehouse'],['lot','Lot'],['batch','Batch'],['expiry','Expiry'],['available','Available'],['status','Status']]},
 treasury:{eyebrow:'Cash visibility',title:'Treasury & Bank Reconciliation',text:'Combine bank balances, unmatched receipts and short-term cash forecasting into one finance view.',action:'generate-forecast',label:'Generate 7-day forecast',stats:[['cashPosition','Cash position','money'],['unmatched','Unmatched'],['expectedInflow','Expected inflow','money'],['expectedOutflow','Expected outflow','money']],table:'transactions',cols:[['date','Date'],['account','Account'],['type','Type'],['amount','Amount','money'],['reference','Reference'],['status','Match status']]},
 contracts:{eyebrow:'Negotiated B2B commerce',title:'Contracts, Rate Agreements & Tenders',text:'Store negotiated customer rates, validity, credit terms and tender opportunities without spreadsheet drift.',action:'tender',label:'Create demo tender',stats:[['active','Active agreements'],['contractValue','Monthly commitment','money'],['openTenders','Open tenders'],['tenderValue','Tender pipeline','money']],table:'agreements',cols:[['agreementNo','Agreement'],['customer','Customer'],['title','Title'],['start','Start'],['end','End'],['minimumMonthly','Monthly minimum','money'],['status','Status']]},
 quality:{eyebrow:'Stock quality gate',title:'Quality Control & Inspection',text:'Inspect incoming/outgoing goods, quarantine failures and prevent rejected stock from quietly becoming sellable.',action:'inspection',label:'Create inspection',stats:[['pending','Pending'],['rejectedQty','Rejected qty'],['quarantineQty','Quarantine qty'],['completed','Completed']],table:'inspections',cols:[['inspectionNo','Inspection'],['type','Type'],['product','Product'],['warehouse','Warehouse'],['received','Received'],['passed','Passed'],['rejected','Rejected'],['status','Status']]},
 'supply-planning':{eyebrow:'Company-wide inventory planning',title:'Advanced Replenishment / S&OP',text:'Balance demand, stock, transfers, safety stock and purchase requirements across locations and scenarios.',action:'generate',label:'Generate base plan',stats:[['scenarios','Scenarios'],['recommendedPurchase','Purchase qty'],['recommendedTransfer','Transfer qty'],['products','Products']],table:'plans',cols:[['scenario','Scenario'],['product','Product'],['fromWarehouse','From'],['toWarehouse','To'],['demand','Demand'],['stock','Stock'],['transfer','Transfer'],['purchase','Purchase']]},
 'service-rma':{eyebrow:'After-sales control',title:'Warranty, RMA & Service',text:'Track serial-linked complaints, warranty validity, repairs, replacements and manufacturer recovery.',action:'ticket',label:'Create demo ticket',stats:[['open','Open tickets'],['warranty','Under warranty'],['rmas','RMAs'],['claimValue','Claims','money']],table:'tickets',cols:[['ticketNo','Ticket'],['customer','Customer'],['product','Product'],['serial','Serial'],['status','Status'],['warranty','Warranty'],['technician','Technician']]},
 expenses:{eyebrow:'Operating spend',title:'Expenses, Petty Cash & Employee Claims',text:'Capture receipts, approval, branch petty cash and payout status so profitability includes real operating cost.',action:'submit',label:'Submit demo claim',stats:[['submitted','Submitted','money'],['approved','Approved','money'],['pettyCash','Petty cash','money'],['claims','Claims']],table:'claims',cols:[['claimNo','Claim'],['employee','Employee'],['category','Category'],['amount','Amount','money'],['date','Date'],['method','Method'],['status','Status']]},
 'report-builder':{eyebrow:'Self-service analytics',title:'Custom Report Builder',text:'Define dimensions, measures, filters and delivery schedules without creating a new developer ticket for every question.',action:'create-report',label:'Create demo report',stats:[['reports','Reports'],['scheduled','Scheduled'],['runs','Runs'],['failed','Failed']],table:'reports',cols:[['name','Report'],['source','Source'],['dimensions','Dimensions','list'],['measures','Measures','list'],['shared','Shared'],['owner','Owner']]},
 'operations-center':{eyebrow:'Production reliability',title:'Operations Control Center',text:'Monitor services, jobs, webhooks and provider health, with retry/replay controls for operational failures.',action:'heartbeat',label:'Run heartbeat',stats:[['healthy','Healthy'],['degraded','Degraded'],['failedJobs','Failed jobs'],['failedWebhooks','Failed webhooks']],table:'services',cols:[['service','Service'],['category','Category'],['status','Status'],['latency','Latency ms'],['message','Message'],['checkedAt','Checked']]}
};
function cell(row,[key,,kind]){const v=row[key];if(kind==='money')return money(v);if(kind==='list')return Array.isArray(v)?v.join(', '):String(v??'—');if(typeof v==='boolean')return v?'Yes':'No';return String(v??'—')}
export default function NextgenModulePage({module}){const{mode}=useAuth();const cfg=configs[module];const[data,setData]=useState(demoNextgen[module]);const[notice,setNotice]=useState('');useEffect(()=>{setData(demoNextgen[module]);if(mode==='api')getApiResource(module).then(setData).catch(()=>{})},[module,mode]);if(!cfg||!data)return null;const act=async()=>{try{let payload={action:cfg.action};if(module==='traceability')payload={...payload,quantity:10};if(module==='contracts')payload={...payload,title:'Demo tender',value:250000};if(module==='quality')payload={...payload,quantity:50};if(module==='service-rma')payload={...payload,complaint:'Demo service request'};if(module==='expenses')payload={...payload,category:'Travel',amount:850,description:'Demo field expense'};if(module==='report-builder')payload={...payload,name:'Demo contribution report',source:'Sales',dimensions:['Customer'],measures:['Revenue']};const r=mode==='api'?await createApiResource(module,payload):{ok:true};setNotice(mode==='api'?`Action completed${r.id?` (#${r.id})`:''}.`:'Demo action previewed. Connect Django to persist changes.');if(mode==='api')getApiResource(module).then(setData).catch(()=>{});}catch(e){setNotice(e.message)}};return <><div className="module-header"><div><span className="eyebrow">{cfg.eyebrow}</span><h1>{cfg.title}</h1><p>{cfg.text}</p></div><button onClick={act}>{cfg.label}</button></div>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid">{cfg.stats.map(([key,label,kind])=><article key={key}><span>{label}</span><strong>{kind==='money'?money(data.summary[key]):data.summary[key]}</strong><small>live company scope</small></article>)}</div><article className="panel module-panel"><div className="panel-head"><div><span>Operational view</span><h3>{cfg.title}</h3></div></div><div className="table-wrap"><table className="data-table module-table"><thead><tr>{cfg.cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{(data[cfg.table]||[]).map((r,i)=><tr key={r.id||i}>{cfg.cols.map(c=><td key={c[0]}>{cell(r,c)}</td>)}</tr>)}</tbody></table></div></article></>}
