import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { createApiResource, getApiResource } from '../services/api';

const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;
const demo = { summary: { cashPosition: 842600, receivable: 472350, payable: 337450, projectedBalance: 977900, consented: false, transactions: 12 }, accounts: [{ id: 1, name: 'Operating account', bank: 'Demo Bank', last4: '1206', type: 'Current', balance: 842600 }], transactions: [], forecast: [{ date: '2026-09-29', inflow: 33739, outflow: 24104, balance: 852235 }, { date: '2026-10-05', inflow: 33739, outflow: 24104, balance: 909645 }], consent: { active: false, source: 'Not connected' } };

export default function OpenFinancePage() {
  const { mode } = useAuth();
  const [data, setData] = useState(demo); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { if (mode !== 'api') { setData(demo); return; } try { setData(await getApiResource('open-finance')); } catch (error) { setNotice(error.message); } };
  useEffect(() => { load(); }, [mode]);
  const action = async (name, payload = {}) => { setBusy(true); try { if (mode === 'api') await createApiResource('open-finance', { action: name, ...payload }); setNotice(name === 'connect' ? 'Open-finance consent recorded. Provider credentials are still required for live bank data.' : name === 'revoke' ? 'Open-finance consent revoked.' : name === 'generate-forecast' ? '14-day cash-flow forecast generated.' : 'Statement rows imported.'); await load(); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const summary = data.summary || demo.summary;
  return <div className="open-finance-page">
    {notice && <div className="inline-notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    <div className="module-header"><div><span className="eyebrow">Consent-based finance</span><h1>Open-finance cash cockpit</h1><p>Combine connected accounts, receivables and payable commitments into one cash-flow view without storing bank credentials.</p></div><div className="open-finance-actions"><button onClick={() => action('generate-forecast')} disabled={busy}>Generate 14-day forecast</button>{summary.consented ? <button className="secondary-btn" onClick={() => action('revoke')} disabled={busy}>Revoke consent</button> : <button className="secondary-btn" onClick={() => action('connect')} disabled={busy}>Connect with consent</button>}</div></div>
    <div className="finance-summary"><article><span>Cash position</span><strong>{money(summary.cashPosition)}</strong><small>connected active accounts</small></article><article><span>Receivables</span><strong>{money(summary.receivable)}</strong><small>expected customer inflow</small></article><article><span>Payables</span><strong>{money(summary.payable)}</strong><small>known supplier commitments</small></article><article><span>Projected balance</span><strong>{money(summary.projectedBalance)}</strong><small>after forecast window</small></article></div>
    <div className="finance-grid"><article className="panel module-panel"><div className="panel-head"><div><span>Bank connections</span><h3>Consent status</h3></div><small>{data.consent?.source || 'Not connected'}</small></div>{(data.accounts || []).map(account => <div className="finance-account" key={account.id}><span className="finance-bank-mark">{account.bank.slice(0, 1)}</span><div><strong>{account.name}</strong><small>{account.bank} · {account.type} · •••• {account.last4 || '----'}</small></div><b>{money(account.balance)}</b></div>)}</article><article className="panel module-panel"><div className="panel-head"><div><span>Liquidity outlook</span><h3>14-day cash projection</h3></div></div><div className="cash-bars">{(data.forecast || []).slice(0, 7).map(row => <div key={row.date}><span>{row.date.slice(5)}</span><i style={{ height: `${Math.max(16, Math.min(100, Number(row.balance || 0) / Math.max(1, Number(summary.projectedBalance || 1)) * 100))}%` }} /><strong>{money(row.balance)}</strong></div>)}</div></article></div>
    <article className="panel module-panel"><div className="panel-head"><div><span>Consent and imported activity</span><h3>Recent bank transactions</h3></div><small>{summary.consented ? 'Consent active' : 'Demo data only until consent is granted'}</small></div><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Date</th><th>Account</th><th>Description</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{(data.transactions || []).length ? data.transactions.map(row => <tr key={row.id}><td>{row.date}</td><td>{row.account}</td><td>{row.description}</td><td>{row.reference || '—'}</td><td className={row.type === 'Debit' ? 'finance-debit' : 'finance-credit'}>{row.type === 'Debit' ? '-' : '+'}{money(row.amount)}</td><td>{row.status}</td></tr>) : <tr><td colSpan="6" className="empty-state">No imported statement rows yet. Connect consent and import through an authorised provider.</td></tr>}</tbody></table></div></article>
  </div>;
}
