import { useMemo, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useApiData } from '../services/useApiData';
import { apiRequest, createApiResource, downloadCsv, importCsv, patchApiResource, postApiAction, uploadAttachment } from '../services/api';
import { demoCustomers, demoDashboard, demoInvoices, demoProducts } from '../data/demoData';
import { demoPurchases, demoSuppliers, demoWarehouses } from '../data/featureData';
import { demoAudit, demoPayments, demoQuotations, demoReports, demoSettings, demoTeam } from '../data/productionData';

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const today = () => new Date().toISOString().slice(0, 10);

function Header({ eyebrow = 'Operations', title, subtitle, action, onAction, search, setSearch, extra }) {
  return <div className="module-header"><div><span className="section-kicker">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="module-actions">{setSearch && <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search…" />}{extra}{action && <button onClick={onAction}>{action}</button>}</div></div>;
}

function Modal({ title, children, onClose }) {
  return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section className="modal-card"><header><div><span className="section-kicker">Client-ready workflow</span><h2>{title}</h2></div><button className="modal-close" onClick={onClose}>×</button></header>{children}</section></div>;
}

function FormActions({ busy, onClose, label = 'Save' }) {
  return <div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button disabled={busy}>{busy ? 'Saving…' : label}</button></div>;
}

function Notice({ text, type = 'success', onClose }) {
  if (!text) return null;
  return <div className={`toast ${type}`}><span>{text}</span><button onClick={onClose}>×</button></div>;
}

function ErrorState({ error }) {
  return error ? <div className="api-error"><strong>Live API issue</strong><span>{error}</span><small>Production mode does not silently switch to demo data.</small></div> : null;
}

function Status({ children }) { return <span className={`feature-badge status-${String(children).toLowerCase().replace(/\s+/g, '-')}`}>{children}</span>; }

function CsvImportButton({ resource, mode, onDone, onError }) {
  const change = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    try {
      if (mode === 'api') {
        const result = await importCsv(resource, file);
        onDone?.(`Imported ${result.rows} rows: ${result.created} created, ${result.updated} updated.`);
      } else onDone?.('Demo mode: CSV import is available when Django is connected.');
    } catch (err) { onError?.(err.message); }
    event.target.value = '';
  };
  return <label className="secondary-btn csv-button">Import CSV<input type="file" accept=".csv,text/csv" onChange={change} hidden /></label>;
}


function AttachmentButton({ mode, module, entityId, notify }) {
  const change = async (event) => {
    const file = event.target.files?.[0]; if (!file) return;
    try {
      if (mode === 'api') { await uploadAttachment(module, entityId, file); notify?.('Attachment uploaded securely.'); }
      else notify?.('Demo mode: attachment upload requires the Django API.');
    } catch (err) { notify?.(err.message); }
    event.target.value = '';
  };
  return <label className="table-action attachment-action">Attach<input hidden type="file" accept=".pdf,.png,.jpg,.jpeg,.csv,.xlsx" onChange={change}/></label>;
}

function BranchCreator({ mode, refresh, notify }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setBusy(true); const payload = Object.fromEntries(new FormData(e.currentTarget).entries());
    try { if (mode === 'api') await createApiResource('branches', payload); notify(mode === 'api' ? 'Branch created.' : 'Demo branch validated.'); setOpen(false); refresh?.(); }
    catch (err) { notify(err.message); } finally { setBusy(false); }
  };
  return <><button className="secondary-btn" onClick={() => setOpen(true)}>Add branch</button>{open && <Modal title="Add company branch" onClose={() => setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Branch code<input name="code" required placeholder="NOI"/></label><label>Name<input name="name" required placeholder="Noida Hub"/></label><label>City<input name="city"/></label><label>GSTIN<input name="gstin"/></label><label>Phone<input name="phone"/></label><label className="full-field">Address<textarea name="address"/></label><FormActions busy={busy} onClose={() => setOpen(false)} label="Create branch"/></form></Modal>}</>;
}

function ProductPage() {
  const { mode } = useAuth();
  const { data, error, refresh } = useApiData('products', demoProducts, 'products');
  const [local, setLocal] = useState([]); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const rows = [...local, ...(data || [])].filter((p) => `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
  const submit = async (e) => {
    e.preventDefault(); setBusy(true); const form = new FormData(e.currentTarget); const payload = Object.fromEntries(form.entries());
    try { if (mode === 'api') await createApiResource('products', payload); else setLocal((x) => [{ id: `demo-${Date.now()}`, ...payload, stock: 0, buy: Number(payload.buy), sell: Number(payload.sell), reorder: Number(payload.reorder), unit: payload.unit || 'pcs' }, ...x]); setNotice(mode === 'api' ? 'Product created in Django.' : 'Demo product created locally for this session.'); setOpen(false); refresh(); } catch (err) { setNotice(err.message); } finally { setBusy(false); }
  };
  return <div><Notice text={notice} onClose={() => setNotice('')} /><Header title="Products & inventory" subtitle="Maintain SKU, GST/HSN, price, barcode and reorder controls from one catalogue." action="Add product" onAction={() => setOpen(true)} search={search} setSearch={setSearch} extra={<div className="row-actions"><CsvImportButton resource="products" mode={mode} onDone={(m)=>{setNotice(m);refresh();}} onError={setNotice}/><button className="secondary-btn" onClick={() => mode === 'api' && downloadCsv('products')}>Export CSV</button></div>} /><ErrorState error={error} />
    <div className="module-summary"><div><span>Visible SKUs</span><strong>{rows.length}</strong><small>company-scoped catalogue</small></div><div><span>Low stock</span><strong>{rows.filter((p) => Number(p.stock) <= Number(p.reorder)).length}</strong><small>reorder attention</small></div><div><span>Stock value</span><strong>{money(rows.reduce((s,p)=>s+Number(p.stock||0)*Number(p.buy||0),0))}</strong><small>purchase cost</small></div></div>
    <article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Product</th><th>GST</th><th>Available</th><th>Buy / Sell</th><th>Barcode</th><th>Status</th></tr></thead><tbody>{rows.map((p)=><tr key={p.id || p.sku}><td><strong>{p.name}</strong><small>{p.sku} · {p.category}</small></td><td>{p.hsn || '—'}<small>{p.gstRate ?? 18}%</small></td><td><strong>{p.stock} {p.unit}</strong><small>reorder {p.reorder}</small></td><td>{money(p.buy)}<small>{money(p.sell)}</small></td><td className="mono-cell">{p.barcode || '—'}</td><td><Status>{Number(p.stock)<=Number(p.reorder)?'Reorder':'Healthy'}</Status></td></tr>)}</tbody></table></div></article>
    {open && <Modal title="Add sellable product" onClose={() => setOpen(false)}><form className="smart-form" onSubmit={submit}><label>SKU<input name="sku" required placeholder="AN-MCB-63" /></label><label>Product name<input name="name" required /></label><label>Category<input name="category" /></label><label>Unit<input name="unit" defaultValue="pcs" /></label><label>Purchase price<input name="buy" type="number" min="0" step="0.01" /></label><label>Sell price<input name="sell" type="number" min="0" step="0.01" /></label><label>Reorder level<input name="reorder" type="number" min="0" /></label><label>Location<input name="location" placeholder="A-01" /></label><label>HSN code<input name="hsn" /></label><label>GST %<input name="gstRate" type="number" defaultValue="18" /></label><label>Barcode<input name="barcode" /></label><FormActions busy={busy} onClose={() => setOpen(false)} label="Create product" /></form></Modal>}
  </div>;
}

function CustomerPage() {
  const { mode } = useAuth(); const { data, error, refresh } = useApiData('customers', demoCustomers, 'customers'); const [local,setLocal]=useState([]); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  const rows=[...local,...(data||[])].filter((c)=>`${c.name} ${c.city} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api')await createApiResource('customers',{...f,credit_limit:Number(f.credit_limit||0)});else setLocal(x=>[{pk:`demo-${Date.now()}`,id:f.code,name:f.name,city:f.city,phone:f.phone,gstin:f.gstin,outstanding:0,limit:Number(f.credit_limit||0),due:'—',status:'Clear'},...x]);setOpen(false);setNotice('Customer created.');refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')} /><Header title="Customers & credit" subtitle="Manage GST details, credit limits, receivables and collection follow-ups." action="Add customer" onAction={()=>setOpen(true)} search={search} setSearch={setSearch} extra={<div className="row-actions"><CsvImportButton resource="customers" mode={mode} onDone={(m)=>{setNotice(m);refresh();}} onError={setNotice}/><button className="secondary-btn" onClick={()=>mode==='api'&&downloadCsv('customers')}>Export CSV</button></div>} /><ErrorState error={error}/><div className="module-summary"><div><span>Customers</span><strong>{rows.length}</strong><small>active accounts</small></div><div><span>Receivable</span><strong>{money(rows.reduce((s,c)=>s+Number(c.outstanding||0),0))}</strong><small>company outstanding</small></div><div><span>Overdue</span><strong>{rows.filter(c=>c.status==='Overdue').length}</strong><small>need collection action</small></div></div><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Customer</th><th>GST / City</th><th>Outstanding</th><th>Credit limit</th><th>Due</th><th>Contact</th></tr></thead><tbody>{rows.map(c=><tr key={c.pk||c.id}><td><strong>{c.name}</strong><small>{c.id}</small></td><td>{c.gstin||'—'}<small>{c.city}</small></td><td><strong>{money(c.outstanding)}</strong><small><Status>{c.status}</Status></small></td><td>{money(c.limit)}</td><td>{c.due}</td><td><a className="whatsapp-link" href={`https://wa.me/91${c.phone}`} target="_blank" rel="noreferrer">WhatsApp ↗</a></td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create customer account" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Customer code<input name="code" required placeholder="C-106"/></label><label>Name<input name="name" required/></label><label>City<input name="city"/></label><label>State<input name="state" defaultValue="Delhi"/></label><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label>GSTIN<input name="gstin"/></label><label>Credit limit<input name="credit_limit" type="number" min="0"/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Create customer"/></form></Modal>}</div>;
}

function OrderPage() {
  const { mode }=useAuth(); const orderData=useApiData('orders',demoDashboard.recentOrders,'orders'); const customerData=useApiData('customers',demoCustomers,'customers'); const productData=useApiData('products',demoProducts,'products'); const warehouseData=useApiData('warehouses',demoWarehouses);
  const [local,setLocal]=useState([]);const[search,setSearch]=useState('');const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState(''); const rows=[...local,...(orderData.data||[])].filter(o=>`${o.id} ${o.customer} ${o.status}`.toLowerCase().includes(search.toLowerCase())); const customers=customerData.data||[];const products=productData.data||[];const warehouses=warehouseData.data?.warehouses||demoWarehouses.warehouses;
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());const product=products.find(p=>String(p.id)===String(f.productId));const customer=customers.find(c=>String(c.pk)===String(f.customerId));const payload={customerId:Number(f.customerId),warehouseId:Number(f.warehouseId),confirm:f.confirm==='on',orderDate:f.orderDate,items:[{product_id:Number(f.productId),quantity:Number(f.quantity),unit_price:Number(f.unitPrice||product?.sell||0)}]};try{if(mode==='api')await createApiResource('orders',payload);else setLocal(x=>[{pk:`demo-${Date.now()}`,id:`SO-DEMO-${String(Date.now()).slice(-4)}`,customer:customer?.name||'Demo customer',total:Number(f.quantity)*Number(f.unitPrice||product?.sell||0),status:f.confirm==='on'?'Confirmed':'Draft',payment:'Credit',date:'Today'},...x]);setOpen(false);setNotice('Order created and stock workflow is ready.');orderData.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  const act=async(o,action)=>{try{if(mode==='api')await postApiAction(`orders/${o.pk}/action/`,{action});setNotice(mode==='api'?`Order ${action} completed.`:`Demo: ${action} action simulated.`);orderData.refresh();}catch(err){setNotice(err.message)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')} /><Header title="B2B order execution" subtitle="Create orders, reserve stock, pack, dispatch and keep payment status connected." action="Create order" onAction={()=>setOpen(true)} search={search} setSearch={setSearch}/><ErrorState error={orderData.error}/><div className="order-board"><div><span>01</span><strong>Draft</strong><small>Customer + lines</small></div><i>→</i><div><span>02</span><strong>Reserve</strong><small>Warehouse availability</small></div><i>→</i><div><span>03</span><strong>Pack</strong><small>Controlled execution</small></div><i>→</i><div><span>04</span><strong>Dispatch</strong><small>Stock movement posted</small></div></div><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Order</th><th>Customer</th><th>Warehouse</th><th>Total</th><th>Status</th><th>Execution</th></tr></thead><tbody>{rows.map(o=><tr key={o.pk||o.id}><td><strong>{o.id}</strong><small>{o.date}</small></td><td>{o.customer}</td><td>{o.warehouse||'Delhi Central'}</td><td>{money(o.total)}</td><td><Status>{o.status}</Status></td><td><div className="row-actions">{!['Confirmed','Processing','Packed','Ready','Dispatched','Cancelled'].includes(o.status)&&<button onClick={()=>act(o,'confirm')}>Confirm</button>}{['Confirmed','Processing'].includes(o.status)&&<button onClick={()=>act(o,'packed')}>Pack</button>}{o.status==='Packed'&&<button onClick={()=>act(o,'ready')}>Ready</button>}{o.status==='Ready'&&<button onClick={()=>act(o,'dispatch')}>Dispatch</button>}</div></td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create sales order" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Customer<select name="customerId" required><option value="">Select customer</option>{customers.map(c=><option key={c.pk||c.id} value={c.pk}>{c.name}</option>)}</select></label><label>Warehouse<select name="warehouseId" required><option value="">Select warehouse</option>{warehouses.map(w=><option key={w.pk||w.id} value={w.pk||w.id}>{w.name}</option>)}</select></label><label>Product<select name="productId" required><option value="">Select product</option>{products.map(p=><option key={p.id||p.sku} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" defaultValue="1" required/></label><label>Unit price<input name="unitPrice" type="number" min="0" step="0.01" placeholder="Uses product sell price if blank"/></label><label>Order date<input name="orderDate" type="date" defaultValue={today()}/></label><label className="check-label"><input name="confirm" type="checkbox"/>Confirm now and reserve stock</label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Create order"/></form></Modal>}</div>;
}

function InvoicePage() {
  const { mode }=useAuth();const invoiceData=useApiData('invoices',demoInvoices,'invoices');const orderData=useApiData('orders',demoDashboard.recentOrders,'orders');const[open,setOpen]=useState(false);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[search,setSearch]=useState('');const rows=(invoiceData.data||[]).filter(i=>`${i.id} ${i.customer} ${i.order}`.toLowerCase().includes(search.toLowerCase()));
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api')await createApiResource('invoices',{orderId:Number(f.orderId),invoiceDate:f.invoiceDate,dueDate:f.dueDate,supplyType:f.supplyType,placeOfSupply:f.placeOfSupply});setNotice(mode==='api'?'GST invoice created and ledger posted.':'Demo invoice workflow simulated.');setOpen(false);invoiceData.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  const openPrint=async(i)=>{if(mode!=='api'){setNotice('Print / Save PDF becomes live when Django is connected.');return;}try{const result=await apiRequest(`/invoices/${i.pk}/print/`);const w=window.open('','_blank');if(w){w.document.open();w.document.write(result.text||'');w.document.close();}}catch(err){setNotice(err.message)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header title="GST invoices" subtitle="Create tax invoices from orders, post receivables and open a print-ready A4 invoice for Save as PDF." action="Create invoice" onAction={()=>setOpen(true)} search={search} setSearch={setSearch}/><ErrorState error={invoiceData.error}/><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Taxable</th><th>GST</th><th>Total</th><th>Status</th><th>Document</th></tr></thead><tbody>{rows.map(i=><tr key={i.pk||i.id}><td><strong>{i.id}</strong><small>{i.date}</small></td><td>{i.customer}<small>{i.gstin}</small></td><td>{money(i.taxable)}</td><td>{money(i.tax)}</td><td><strong>{money(i.total)}</strong></td><td><Status>{i.status}</Status></td><td><div className="row-actions"><button className="table-action" onClick={()=>openPrint(i)}>Print / PDF</button><AttachmentButton mode={mode} module="invoice" entityId={i.pk||i.id} notify={setNotice}/></div></td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create GST invoice" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Sales order<select name="orderId" required><option value="">Select uninvoiced order</option>{(orderData.data||[]).map(o=><option key={o.pk||o.id} value={o.pk}>{o.id} · {o.customer} · {money(o.total)}</option>)}</select></label><label>Invoice date<input name="invoiceDate" type="date" defaultValue={today()}/></label><label>Due date<input name="dueDate" type="date"/></label><label>Supply type<select name="supplyType"><option>Intra-state</option><option>Inter-state</option></select></label><label>Place of supply<input name="placeOfSupply" defaultValue="Delhi"/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Generate invoice"/></form></Modal>}</div>;
}

function PurchasePage() {
  const {mode}=useAuth();const purchaseData=useApiData('purchases',demoPurchases,'purchases');const supplierData=useApiData('suppliers',demoSuppliers,'suppliers');const productData=useApiData('products',demoProducts,'products');const whData=useApiData('warehouses',demoWarehouses);const[open,setOpen]=useState(false);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[search,setSearch]=useState('');const rows=(purchaseData.data||[]).filter(p=>`${p.id} ${p.supplier} ${p.status}`.toLowerCase().includes(search.toLowerCase()));const suppliers=supplierData.data||[];const products=productData.data||[];const wh=whData.data?.warehouses||demoWarehouses.warehouses;
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api')await createApiResource('purchases',{supplierId:Number(f.supplierId),warehouseId:Number(f.warehouseId),expectedDate:f.expectedDate,items:[{productId:Number(f.productId),quantity:Number(f.quantity),unitPrice:Number(f.unitPrice)}]});setNotice(mode==='api'?'Purchase order created.':'Demo PO simulated.');setOpen(false);purchaseData.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  const act=async(p,action)=>{try{if(mode==='api')await postApiAction(`purchases/${p.pk}/action/`,{action});setNotice(mode==='api'?`${action} completed for ${p.id}.`:`Demo ${action} simulated.`);purchaseData.refresh();}catch(err){setNotice(err.message)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header eyebrow="Procurement" title="Purchase orders & GRN" subtitle="Approve procurement, receive goods into a selected warehouse and automatically post stock and supplier payable." action="New purchase order" onAction={()=>setOpen(true)} search={search} setSearch={setSearch}/><ErrorState error={purchaseData.error}/><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>PO</th><th>Supplier</th><th>Warehouse</th><th>Total</th><th>Expected</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(p=><tr key={p.pk||p.id}><td><strong>{p.id}</strong><small>{p.date}</small></td><td>{p.supplier}</td><td>{p.warehouse||'Delhi Central'}</td><td>{money(p.total)}</td><td>{p.expected}</td><td><Status>{p.status}</Status></td><td><div className="row-actions">{p.status==='Draft'&&<button onClick={()=>act(p,'approve')}>Approve</button>}{['Approved','Partial'].includes(p.status)&&<button onClick={()=>act(p,'receive')}>Receive GRN</button>}</div></td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create purchase order" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Supplier<select name="supplierId" required><option value="">Select supplier</option>{suppliers.map(s=><option key={s.pk||s.id} value={s.pk}>{s.name}</option>)}</select></label><label>Receiving warehouse<select name="warehouseId" required><option value="">Select warehouse</option>{wh.map(w=><option key={w.pk||w.id} value={w.pk||w.id}>{w.name}</option>)}</select></label><label>Product<select name="productId" required><option value="">Select product</option>{products.map(p=><option key={p.id||p.sku} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Unit cost<input name="unitPrice" type="number" min="0" step="0.01" required/></label><label>Expected date<input name="expectedDate" type="date"/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Create PO"/></form></Modal>}</div>;
}

function WarehousePage() {
  const {mode}=useAuth();const whData=useApiData('warehouses',demoWarehouses);const productData=useApiData('products',demoProducts,'products');const[open,setOpen]=useState(false);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const data=whData.data||demoWarehouses;const warehouses=data.warehouses||[];const transfers=data.transfers||[];
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api')await createApiResource('warehouses',{kind:'transfer',fromWarehouseId:Number(f.fromWarehouseId),toWarehouseId:Number(f.toWarehouseId),items:[{productId:Number(f.productId),quantity:Number(f.quantity)}]});setNotice(mode==='api'?'Transfer created.':'Demo transfer simulated.');setOpen(false);whData.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  const act=async(t,action)=>{try{if(mode==='api')await postApiAction(`transfers/${t.pk}/action/`,{action});setNotice(mode==='api'?`Transfer ${action} completed.`:`Demo transfer ${action} simulated.`);whData.refresh();}catch(err){setNotice(err.message)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header eyebrow="Inventory network" title="Multi-warehouse stock" subtitle="Trace transfers from request through dispatch and receipt, with inventory movements posted at both locations." action="New transfer" onAction={()=>setOpen(true)}/><ErrorState error={whData.error}/><div className="warehouse-grid">{warehouses.map(w=><article className="warehouse-card" key={w.pk||w.id}><span>{w.id}</span><strong>{w.name}</strong><small>{w.city}</small><div><b>{w.stock}</b> units <em>{w.reserved} reserved</em></div></article>)}</div><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Transfer</th><th>From</th><th>To</th><th>Units</th><th>Status</th><th>Action</th></tr></thead><tbody>{transfers.map(t=><tr key={t.pk||t.id}><td><strong>{t.id}</strong><small>{t.date}</small></td><td>{t.from}</td><td>{t.to}</td><td>{t.units}</td><td><Status>{t.status}</Status></td><td><div className="row-actions">{t.status==='Draft'&&<button onClick={()=>act(t,'approve')}>Approve</button>}{t.status==='Approved'&&<button onClick={()=>act(t,'dispatch')}>Dispatch</button>}{t.status==='In Transit'&&<button onClick={()=>act(t,'receive')}>Receive</button>}</div></td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create stock transfer" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>From warehouse<select name="fromWarehouseId" required>{warehouses.map(w=><option key={w.pk||w.id} value={w.pk||w.id}>{w.name}</option>)}</select></label><label>To warehouse<select name="toWarehouseId" required>{warehouses.map(w=><option key={w.pk||w.id} value={w.pk||w.id}>{w.name}</option>)}</select></label><label>Product<select name="productId" required>{(productData.data||[]).map(p=><option key={p.id||p.sku} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" required/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Create transfer"/></form></Modal>}</div>;
}

function QuotationPage() {
  const {mode}=useAuth();const data=useApiData('quotations',demoQuotations,'quotations');const customers=useApiData('customers',demoCustomers,'customers');const products=useApiData('products',demoProducts,'products');const warehouses=useApiData('warehouses',demoWarehouses);const[open,setOpen]=useState(false);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const rows=data.data||[];
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api')await createApiResource('quotations',{customerId:Number(f.customerId),warehouseId:Number(f.warehouseId),validUntil:f.validUntil,items:[{productId:Number(f.productId),quantity:Number(f.quantity),unitPrice:Number(f.unitPrice)}]});setNotice(mode==='api'?'Quotation created.':'Demo quotation created.');setOpen(false);data.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  const convert=async(q)=>{try{if(mode==='api')await postApiAction(`quotations/${q.pk}/action/`,{action:'convert'});setNotice(mode==='api'?'Quotation converted to an order.':'Demo conversion simulated.');data.refresh();}catch(err){setNotice(err.message)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header title="Quotations" subtitle="Price customer enquiries and convert accepted quotes into real sales orders without retyping the lines." action="New quotation" onAction={()=>setOpen(true)}/><ErrorState error={data.error}/><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Quote</th><th>Customer</th><th>Valid until</th><th>Total</th><th>Status</th><th>Conversion</th></tr></thead><tbody>{rows.map(q=><tr key={q.pk||q.id}><td><strong>{q.id}</strong><small>{q.date}</small></td><td>{q.customer}</td><td>{q.validUntil||'—'}</td><td>{money(q.total)}</td><td><Status>{q.status}</Status></td><td>{q.order?<strong>{q.order}</strong>:<button className="table-action" onClick={()=>convert(q)}>Convert to order</button>}</td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create B2B quotation" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Customer<select name="customerId" required>{(customers.data||[]).map(c=><option key={c.pk||c.id} value={c.pk}>{c.name}</option>)}</select></label><label>Warehouse<select name="warehouseId">{(warehouses.data?.warehouses||demoWarehouses.warehouses).map(w=><option key={w.pk||w.id} value={w.pk||w.id}>{w.name}</option>)}</select></label><label>Product<select name="productId" required>{(products.data||[]).map(p=><option key={p.id||p.sku} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" required/></label><label>Unit price<input name="unitPrice" type="number" min="0" step="0.01" required/></label><label>Valid until<input name="validUntil" type="date"/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Create quotation"/></form></Modal>}</div>;
}

function PaymentsPage() {
  const {mode}=useAuth();const data=useApiData('payments',demoPayments,'payments');const customers=useApiData('customers',demoCustomers,'customers');const suppliers=useApiData('suppliers',demoSuppliers,'suppliers');const[open,setOpen]=useState(false);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[partyType,setPartyType]=useState('customer');
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());const payload={partyType,amount:Number(f.amount),method:f.method,reference:f.reference,date:f.date,notes:f.notes,...(partyType==='customer'?{customerId:Number(f.customerId)}:{supplierId:Number(f.supplierId)})};try{if(mode==='api')await createApiResource('payments',payload);setNotice(mode==='api'?'Payment posted to ledger.':'Demo payment simulated.');setOpen(false);data.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header title="Payments & collections" subtitle="Post customer receipts and supplier payments so balances update instead of living in someone’s mental spreadsheet." action="Record payment" onAction={()=>setOpen(true)}/><ErrorState error={data.error}/><div className="module-summary"><div><span>Recent transactions</span><strong>{(data.data||[]).length}</strong><small>customer + supplier</small></div><div><span>Customer collected</span><strong>{money((data.data||[]).filter(x=>x.partyType==='customer').reduce((s,x)=>s+Number(x.amount),0))}</strong><small>loaded history</small></div><div><span>Supplier paid</span><strong>{money((data.data||[]).filter(x=>x.partyType==='supplier').reduce((s,x)=>s+Number(x.amount),0))}</strong><small>loaded history</small></div></div><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Reference</th><th>Party</th><th>Type</th><th>Method</th><th>Amount</th><th>Date</th></tr></thead><tbody>{(data.data||[]).map(p=><tr key={p.id}><td><strong>{p.id}</strong></td><td>{p.party}</td><td><Status>{p.partyType}</Status></td><td>{p.method}</td><td><strong>{money(p.amount)}</strong></td><td>{p.date}</td></tr>)}</tbody></table></div></article>{open&&<Modal title="Record money movement" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Party type<select value={partyType} onChange={e=>setPartyType(e.target.value)}><option value="customer">Customer receipt</option><option value="supplier">Supplier payment</option></select></label>{partyType==='customer'?<label>Customer<select name="customerId" required>{(customers.data||[]).map(c=><option key={c.pk||c.id} value={c.pk}>{c.name}</option>)}</select></label>:<label>Supplier<select name="supplierId" required>{(suppliers.data||[]).map(s=><option key={s.pk||s.id} value={s.pk}>{s.name}</option>)}</select></label>}<label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Method<select name="method"><option>UPI</option><option>Bank</option><option>Cash</option><option>Cheque</option></select></label><label>Reference<input name="reference" placeholder="UTR / cheque number"/></label><label>Date<input name="date" type="date" defaultValue={today()}/></label><label className="full-field">Notes<textarea name="notes"/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Post payment"/></form></Modal>}</div>;
}

function ReportsPage() {
  const {mode}=useAuth();const {data,error}=useApiData('reports',demoReports,'reports');const r=data||demoReports;const exportIt=async(resource)=>{if(mode==='api')await downloadCsv(resource);};
  return <div><Header eyebrow="Management reporting" title="Business reports" subtitle="Sales, collections, purchases, working capital and stock value from the same transactional database." extra={<div className="row-actions"><button className="secondary-btn" onClick={()=>exportIt('orders')}>Orders CSV</button><button className="secondary-btn" onClick={()=>exportIt('ledger')}>Ledger CSV</button></div>}/><ErrorState error={error}/><div className="report-grid"><article><span>Month sales</span><strong>{money(r.sales)}</strong><small>sales orders</small></article><article><span>Collections</span><strong>{money(r.collections)}</strong><small>customer receipts</small></article><article><span>Purchases</span><strong>{money(r.purchases)}</strong><small>purchase orders</small></article><article><span>Receivable</span><strong>{money(r.receivable)}</strong><small>customer outstanding</small></article><article><span>Payable</span><strong>{money(r.payable)}</strong><small>supplier outstanding</small></article><article><span>Stock value</span><strong>{money(r.stockValue)}</strong><small>purchase cost</small></article></div><article className="panel module-panel"><div className="panel-head"><div><span>Customers</span><h3>Top sales accounts</h3></div></div><div className="metric-bars">{(r.topCustomers||[]).map((x,i)=><div key={x.name}><span>{i+1}. {x.name}</span><i><b style={{width:`${Math.min(100,(x.sales/(r.topCustomers?.[0]?.sales||1))*100)}%`}}/></i><strong>{money(x.sales)}</strong></div>)}</div></article></div>;
}

function TeamPage() {
  const {mode}=useAuth();const data=useApiData('team',demoTeam,'team');const[open,setOpen]=useState(false);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api')await createApiResource('team',f);setNotice(mode==='api'?'Team account created. Copy the temporary password securely.':'Demo team invite simulated.');setOpen(false);data.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  const toggle=async(u)=>{try{if(mode==='api')await patchApiResource(`team/${u.id}/`,{active:!u.active});setNotice(mode==='api'?'Account status updated.':'Demo account toggle simulated.');data.refresh();}catch(err){setNotice(err.message)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header eyebrow="Access control" title="Team & roles" subtitle="Create employee accounts, assign operating roles and deactivate access without sharing passwords." action="Add team member" onAction={()=>setOpen(true)}/><ErrorState error={data.error}/><article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Branch</th><th>Status</th><th>Control</th></tr></thead><tbody>{(data.data||[]).map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><Status>{u.role}</Status></td><td>{u.branch}</td><td>{u.active?'Active':'Disabled'}</td><td><button className="table-action" onClick={()=>toggle(u)}>{u.active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></article>{open&&<Modal title="Create employee access" onClose={()=>setOpen(false)}><form className="smart-form" onSubmit={submit}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone<input name="phone"/></label><label>Role<select name="role"><option>MANAGER</option><option>SALES</option><option>WAREHOUSE</option><option>ACCOUNTANT</option></select></label><label>Temporary password<input name="temporaryPassword" defaultValue="ChangeMe123!"/></label><FormActions busy={busy} onClose={()=>setOpen(false)} label="Create access"/></form></Modal>}</div>;
}

function SettingsPage() {
  const {mode,user,setUser}=useAuth();const data=useApiData('settings',demoSettings,'settings');const settings=data.data||demoSettings;const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  const submit=async(e)=>{e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{if(mode==='api'){const result=await patchApiResource('settings/',{...f,financial_year_start:Number(f.financial_year_start||4)});setUser({...user,business:result.settings.name,branding:{logo:result.settings.logo_url,state:result.settings.state,invoicePrefix:result.settings.invoice_prefix}});const nextUser={...user,business:result.settings.name,branding:{logo:result.settings.logo_url,state:result.settings.state,invoicePrefix:result.settings.invoice_prefix},mode:'api'}; localStorage.setItem('setustock_auth',JSON.stringify(nextUser));}setNotice(mode==='api'?'Company settings saved.':'Demo settings form validated. Connect Django to persist them.');data.refresh();}catch(err){setNotice(err.message)}finally{setBusy(false)}};
  return <div><Notice text={notice} onClose={()=>setNotice('')}/><Header eyebrow="Onboarding & branding" title="Business settings" subtitle="Company identity, GST, bank/UPI, invoice numbering and client branding live here." extra={<BranchCreator mode={mode} refresh={data.refresh} notify={setNotice}/>}/><ErrorState error={data.error}/><form className="settings-form panel" onSubmit={submit}><div className="settings-section"><span className="section-kicker">Company</span><h3>Legal & contact details</h3><div className="smart-form"><label>Business name<input name="name" defaultValue={settings.name}/></label><label>GSTIN<input name="gstin" defaultValue={settings.gstin}/></label><label>PAN<input name="pan" defaultValue={settings.pan}/></label><label>State<input name="state" defaultValue={settings.state}/></label><label className="full-field">Address<textarea name="address" defaultValue={settings.address}/></label><label>Phone<input name="phone" defaultValue={settings.phone}/></label><label>Email<input name="email" defaultValue={settings.email}/></label></div></div><div className="settings-section"><span className="section-kicker">Collections</span><h3>Bank & invoice defaults</h3><div className="smart-form"><label>Bank name<input name="bank_name" defaultValue={settings.bank_name}/></label><label>Account<input name="bank_account" defaultValue={settings.bank_account}/></label><label>IFSC<input name="ifsc" defaultValue={settings.ifsc}/></label><label>UPI ID<input name="upi_id" defaultValue={settings.upi_id}/></label><label>Invoice prefix<input name="invoice_prefix" defaultValue={settings.invoice_prefix}/></label><label>Financial year starts<input name="financial_year_start" type="number" min="1" max="12" defaultValue={settings.financial_year_start}/></label><label className="full-field">Logo URL<input name="logo_url" defaultValue={settings.logo_url}/></label></div></div><button disabled={busy}>{busy?'Saving…':'Save business settings'}</button></form><div className="branch-cards">{(settings.branches||[]).map(b=><article key={b.id}><span>{b.code}</span><strong>{b.name}</strong><small>{b.city} · {b.gstin}</small></article>)}</div></div>;
}

function AuditPage() {
  const {data,error}=useApiData('audit',demoAudit,'audit');return <div><Header eyebrow="Accountability" title="Audit log" subtitle="See who changed stock, payments, orders, user access and company settings."/><ErrorState error={error}/><article className="panel module-panel"><div className="audit-list">{(data||[]).map(x=><div key={x.id}><span className="audit-action">{x.action}</span><section><strong>{x.summary}</strong><small>{x.entity} #{x.entityId} · {x.actor}</small></section><time>{new Date(x.time).toLocaleString('en-IN')}</time></div>)}</div></article></div>;
}

export default function ProductionModulePage({ module }) {
  if (module==='products'||module==='inventory') return <ProductPage/>;
  if (module==='customers') return <CustomerPage/>;
  if (module==='orders') return <OrderPage/>;
  if (module==='invoices') return <InvoicePage/>;
  if (module==='purchases') return <PurchasePage/>;
  if (module==='warehouses') return <WarehousePage/>;
  if (module==='quotations') return <QuotationPage/>;
  if (module==='payments') return <PaymentsPage/>;
  if (module==='reports') return <ReportsPage/>;
  if (module==='team') return <TeamPage/>;
  if (module==='settings') return <SettingsPage/>;
  if (module==='audit') return <AuditPage/>;
  return null;
}
