import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { getApiResource, createApiResource } from '../services/api';
import { demoCrm, demoSchemes, demoGstCockpit, demoProcurement, demoFleet, demoCredit, demoSecurity, demoIntegrations, demoExecutiveBi } from '../data/strategicData';
const money=(v)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
const Table=({columns,rows})=><div className="table-wrap"><table className="data-table module-table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):String(r[c.key]??'—')}</td>)}</tr>)}</tbody></table></div>;
const Head=({eyebrow,title,text,action,label})=><div className="module-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action&&<button onClick={action}>{label}</button>}</div>;
function CRM({mode}){const[data,setData]=useState(demoCrm);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('crm').then(setData).catch(()=>{})},[mode]);const add=async()=>{try{if(mode==='api')await createApiResource('crm',{action:'lead',name:'Demo Prospect',business:'NCR Demo Electricals',source:'Referral',territory:'Delhi NCR',value:125000});setNotice('Lead created in the sales pipeline.');}catch(e){setNotice(e.message)}};return <><Head eyebrow="Revenue pipeline" title="CRM & sales pipeline" text="Capture prospects, follow-ups, quotation-stage opportunities and won/lost reasons before they become customers." action={add} label="Add demo lead"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Open pipeline</span><strong>{money(data.summary.pipelineValue)}</strong><small>active opportunities</small></article><article><span>Won value</span><strong>{money(data.summary.wonValue)}</strong><small>converted pipeline</small></article><article><span>Conversion</span><strong>{data.summary.conversion}%</strong><small>lead-to-win</small></article></div><article className="panel module-panel"><div className="panel-head"><div><span>Opportunity board</span><h3>Active leads</h3></div></div><Table columns={[{key:'leadNo',label:'Lead'},{key:'business',label:'Business'},{key:'status',label:'Stage'},{key:'source',label:'Source'},{key:'value',label:'Value',render:r=>money(r.value)},{key:'owner',label:'Owner'}]} rows={data.leads}/></article></>}

function Schemes({mode}){const[data,setData]=useState(demoSchemes);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('schemes').then(setData).catch(()=>{})},[mode]);const claim=async()=>{try{if(mode==='api'&&data.schemes[0])await createApiResource('schemes',{action:'submit-claim',schemeId:data.schemes[0].id,eligibleValue:500000});setNotice('Scheme claim calculated and queued with evidence trail.')}catch(e){setNotice(e.message)}};return <><Head eyebrow="Distributor economics" title="Manufacturer schemes & claims" text="Track target slabs, rebates, free-quantity programs and claim settlement without spreadsheet archaeology." action={claim} label="Calculate demo claim"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Active schemes</span><strong>{data.summary.active}</strong><small>current programs</small></article><article><span>Accrued claims</span><strong>{money(data.summary.accrued)}</strong><small>expected manufacturer income</small></article><article><span>Claims</span><strong>{data.summary.claims}</strong><small>tracked settlements</small></article></div><article className="panel module-panel"><Table columns={[{key:'name',label:'Scheme'},{key:'supplier',label:'Manufacturer'},{key:'type',label:'Type'},{key:'target',label:'Target',render:r=>money(r.target)},{key:'rebate',label:'Rebate',render:r=>`${r.rebate}%`},{key:'end',label:'Ends'}]} rows={data.schemes}/></article><article className="panel module-panel"><Table columns={[{key:'claimNo',label:'Claim'},{key:'scheme',label:'Scheme'},{key:'eligible',label:'Eligible',render:r=>money(r.eligible)},{key:'amount',label:'Claim',render:r=>money(r.amount)},{key:'status',label:'Status'}]} rows={data.claims}/></article></>}


function GstCockpit({mode}){const[data,setData]=useState(demoGstCockpit);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('gst-cockpit').then(setData).catch(()=>{})},[mode]);const match=async()=>{try{if(mode==='api')await createApiResource('gst-cockpit',{action:'import',invoiceNo:`IMS-DEMO-${Date.now()}`,booksTax:18440,portalTax:18440});setNotice('IMS-style reconciliation row imported and matched.')}catch(e){setNotice(e.message)}};return <><Head eyebrow="Tax control" title="GST compliance cockpit" text="Reconcile purchase invoices against portal/IMS data, surface missing credits and document every resolution." action={match} label="Import demo match"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Matched</span><strong>{data.summary.matched}</strong><small>supplier invoices</small></article><article><span>Mismatches</span><strong>{data.summary.mismatch}</strong><small>review required</small></article><article><span>Tax difference</span><strong>{money(data.summary.taxDifference)}</strong><small>at-risk ITC</small></article></div><article className="panel module-panel"><Table columns={[{key:'invoiceNo',label:'Invoice'},{key:'supplier',label:'Supplier'},{key:'gstin',label:'GSTIN'},{key:'booksTax',label:'Books tax',render:r=>money(r.booksTax)},{key:'portalTax',label:'Portal tax',render:r=>money(r.portalTax)},{key:'difference',label:'Difference',render:r=>money(r.difference)},{key:'status',label:'Status'}]} rows={data.items}/></article></>}


function Procurement({mode}){const[data,setData]=useState(demoProcurement);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('procurement-intelligence').then(setData).catch(()=>{})},[mode]);const calc=async()=>{try{if(mode==='api')await createApiResource('procurement-intelligence',{action:'recalculate'});setNotice('Vendor scores and low-stock purchase recommendations recalculated.')}catch(e){setNotice(e.message)}};return <><Head eyebrow="Buy smarter" title="Smart procurement & vendor scorecards" text="Combine stock need with supplier price, lead time, fill rate, quality and reliability before raising a PO." action={calc} label="Recalculate"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Scored vendors</span><strong>{data.summary.vendors}</strong><small>supplier performance</small></article><article><span>Open recommendations</span><strong>{data.summary.openRecommendations}</strong><small>buyer review</small></article><article><span>Suggested spend</span><strong>{money(data.summary.recommendedSpend)}</strong><small>current purchase plan</small></article></div><article className="panel module-panel"><Table columns={[{key:'supplier',label:'Supplier'},{key:'score',label:'Score'},{key:'fillRate',label:'Fill rate',render:r=>`${r.fillRate}%`},{key:'onTime',label:'On-time',render:r=>`${r.onTime}%`},{key:'quality',label:'Quality',render:r=>`${r.quality}%`},{key:'leadDays',label:'Lead days'}]} rows={data.vendors}/></article><article className="panel module-panel"><Table columns={[{key:'sku',label:'SKU'},{key:'product',label:'Product'},{key:'supplier',label:'Recommended vendor'},{key:'qty',label:'Qty'},{key:'unitCost',label:'Unit cost',render:r=>money(r.unitCost)},{key:'status',label:'Status'}]} rows={data.recommendations}/></article></>}


function Fleet({mode}){const[data,setData]=useState(demoFleet);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('fleet-routes').then(setData).catch(()=>{})},[mode]);const optimize=async()=>{try{const r=mode==='api'?await createApiResource('fleet-routes',{action:'optimize'}):{stops:12,km:64};setNotice(`Route planned with ${r.stops||12} stops and about ${r.km||64} km.`)}catch(e){setNotice(e.message)}};return <><Head eyebrow="Last-mile economics" title="Fleet & route optimisation" text="Plan delivery runs around capacity, customer area, service priority and cost-per-kilometre." action={optimize} label="Optimise route"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Vehicles</span><strong>{data.summary.vehicles}</strong><small>active fleet</small></article><article><span>Open routes</span><strong>{data.summary.planned}</strong><small>planned / running</small></article><article><span>Estimated cost</span><strong>{money(data.summary.cost)}</strong><small>{data.summary.km} km planned</small></article></div><article className="panel module-panel"><Table columns={[{key:'vehicleNo',label:'Vehicle'},{key:'type',label:'Type'},{key:'driver',label:'Driver'},{key:'capacityKg',label:'Capacity kg'},{key:'costPerKm',label:'₹ / km',render:r=>money(r.costPerKm)}]} rows={data.vehicles}/></article><article className="panel module-panel"><Table columns={[{key:'routeNo',label:'Route'},{key:'date',label:'Date'},{key:'vehicle',label:'Vehicle'},{key:'warehouse',label:'Origin'},{key:'km',label:'Km'},{key:'cost',label:'Cost',render:r=>money(r.cost)},{key:'score',label:'Optimisation'},{key:'status',label:'Status'}]} rows={data.routes}/></article></>}


function CreditRisk({mode}){const[data,setData]=useState(demoCredit);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('credit-risk').then(setData).catch(()=>{})},[mode]);const rescore=async()=>{try{const r=mode==='api'?await createApiResource('credit-risk',{action:'rescore'}):{scored:data.scores.length};setNotice(`${r.scored} customer credit profiles recalculated from ledger and utilisation.`)}catch(e){setNotice(e.message)}};return <><Head eyebrow="Working-capital control" title="Credit scoring & embedded finance" text="Explain trade-credit risk using payment behaviour, utilisation and overdue exposure, then prepare finance applications without hiding the factors." action={rescore} label="Recalculate scores"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Customers scored</span><strong>{data.summary.scored}</strong><small>trade-credit profiles</small></article><article><span>High risk</span><strong>{data.summary.highRisk}</strong><small>needs review</small></article><article><span>Finance pipeline</span><strong>{money(data.summary.financePipeline)}</strong><small>readiness only</small></article></div><article className="panel module-panel"><Table columns={[{key:'customer',label:'Customer'},{key:'score',label:'Score'},{key:'risk',label:'Risk'},{key:'outstanding',label:'Outstanding',render:r=>money(r.outstanding)},{key:'utilisation',label:'Utilisation',render:r=>`${r.utilisation}%`},{key:'overdue90',label:'90+ overdue',render:r=>money(r.overdue90)},{key:'suggestedLimit',label:'Suggested limit',render:r=>money(r.suggestedLimit)}]} rows={data.scores}/></article></>}


function SecurityCenter({mode}){const[data,setData]=useState(demoSecurity);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('security-center').then(setData).catch(()=>{})},[mode]);const mfa=async()=>{try{const r=mode==='api'?await createApiResource('security-center',{action:'enable-mfa'}):{enabled:true};setNotice(r.enabled?'MFA enrollment created. In production, complete authenticator verification before enforcement.':'Unable to enable MFA.')}catch(e){setNotice(e.message)}};return <><Head eyebrow="Enterprise controls" title="Security & privacy administration" text="Manage MFA readiness, trusted devices, security events, consent records and data-subject request workflows. These controls support privacy operations; they are not a legal compliance certificate." action={mfa} label="Enable MFA demo"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>MFA enabled</span><strong>{data.summary.mfaEnabled}/{data.summary.users}</strong><small>staff coverage</small></article><article><span>Trusted devices</span><strong>{data.summary.trustedDevices}</strong><small>known endpoints</small></article><article><span>Open privacy requests</span><strong>{data.summary.openPrivacyRequests}</strong><small>workflow queue</small></article></div><article className="panel module-panel"><Table columns={[{key:'user',label:'User'},{key:'name',label:'Device'},{key:'ip',label:'Last IP'},{key:'trusted',label:'Trusted',render:r=>r.trusted?'Yes':'No'},{key:'lastSeen',label:'Last seen'}]} rows={data.devices}/></article><article className="panel module-panel"><Table columns={[{key:'type',label:'Security event'},{key:'severity',label:'Severity'},{key:'user',label:'User'},{key:'ip',label:'IP'},{key:'createdAt',label:'Time'}]} rows={data.events}/></article></>}


function Integrations({mode}){const[data,setData]=useState(demoIntegrations);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('integrations').then(setData).catch(()=>{})},[mode]);const key=async()=>{try{const r=mode==='api'?await createApiResource('integrations',{action:'api-key',name:'Demo website',scopes:['orders:write']}):{prefix:'ssk_demo'};setNotice(`API key created (${r.prefix||'demo'}…). Live API returns the secret once.`)}catch(e){setNotice(e.message)}};return <><Head eyebrow="Composable platform" title="Integration hub & public API" text="Manage connectors, scoped API keys, webhook subscriptions and delivery health from one boundary instead of scattering credentials through business logic." action={key} label="Create API key"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Connected</span><strong>{data.summary.connected}/{data.summary.connectors}</strong><small>integration health</small></article><article><span>API keys</span><strong>{data.summary.apiKeys}</strong><small>scoped clients</small></article><article><span>Failed deliveries</span><strong>{data.summary.failedDeliveries}</strong><small>retry attention</small></article></div><article className="panel module-panel"><Table columns={[{key:'provider',label:'Provider'},{key:'name',label:'Connector'},{key:'status',label:'Status'},{key:'lastSync',label:'Last sync'},{key:'lastError',label:'Last error'}]} rows={data.connectors}/></article><article className="panel module-panel"><Table columns={[{key:'name',label:'API client'},{key:'prefix',label:'Key prefix'},{key:'scopes',label:'Scopes',render:r=>r.scopes.join(', ')},{key:'lastUsed',label:'Last used'}]} rows={data.apiKeys}/></article></>}


function ExecutiveBI({mode}){const[data,setData]=useState(demoExecutiveBi);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('executive-bi').then(setData).catch(()=>{})},[mode]);const rebuild=async()=>{try{const r=mode==='api'?await createApiResource('executive-bi',{}):{rebuilt:data.rows.length};setNotice(`Profitability model rebuilt for ${r.rebuilt} customer entities.`)}catch(e){setNotice(e.message)}};return <><Head eyebrow="Beyond revenue" title="Executive BI & profitability" text="Measure contribution profit after product cost, discounts and returns so large customers are not automatically mistaken for good customers." action={rebuild} label="Rebuild profitability"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Revenue</span><strong>{money(data.summary.revenue)}</strong><small>period sales</small></article><article><span>Contribution</span><strong>{money(data.summary.contribution)}</strong><small>after modeled costs</small></article><article><span>Contribution margin</span><strong>{data.summary.margin}%</strong><small>economic quality</small></article></div><article className="panel module-panel"><Table columns={[{key:'entity',label:'Customer'},{key:'revenue',label:'Revenue',render:r=>money(r.revenue)},{key:'cogs',label:'COGS',render:r=>money(r.cogs)},{key:'discounts',label:'Discounts',render:r=>money(r.discounts)},{key:'returns',label:'Returns',render:r=>money(r.returns)},{key:'contribution',label:'Contribution',render:r=>money(r.contribution)},{key:'margin',label:'Margin',render:r=>`${r.margin}%`}]} rows={data.rows}/></article></>}

export default function StrategicModulePage({module}){const{mode}=useAuth();if(module==='crm')return <CRM mode={mode}/>;if(module==='schemes')return <Schemes mode={mode}/>;if(module==='gst-cockpit')return <GstCockpit mode={mode}/>;if(module==='procurement-intelligence')return <Procurement mode={mode}/>;if(module==='fleet-routes')return <Fleet mode={mode}/>;if(module==='credit-risk')return <CreditRisk mode={mode}/>;if(module==='security-center')return <SecurityCenter mode={mode}/>;if(module==='integrations')return <Integrations mode={mode}/>;if(module==='executive-bi')return <ExecutiveBI mode={mode}/>;return null;}
