import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { getApiResource, createApiResource } from '../services/api';
import { demoCrm } from '../data/strategicData';
const money=(v)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
const Table=({columns,rows})=><div className="table-wrap"><table className="data-table module-table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):String(r[c.key]??'—')}</td>)}</tr>)}</tbody></table></div>;
const Head=({eyebrow,title,text,action,label})=><div className="module-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action&&<button onClick={action}>{label}</button>}</div>;
function CRM({mode}){const[data,setData]=useState(demoCrm);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('crm').then(setData).catch(()=>{})},[mode]);const add=async()=>{try{if(mode==='api')await createApiResource('crm',{action:'lead',name:'Demo Prospect',business:'NCR Demo Electricals',source:'Referral',territory:'Delhi NCR',value:125000});setNotice('Lead created in the sales pipeline.');}catch(e){setNotice(e.message)}};return <><Head eyebrow="Revenue pipeline" title="CRM & sales pipeline" text="Capture prospects, follow-ups, quotation-stage opportunities and won/lost reasons before they become customers." action={add} label="Add demo lead"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Open pipeline</span><strong>{money(data.summary.pipelineValue)}</strong><small>active opportunities</small></article><article><span>Won value</span><strong>{money(data.summary.wonValue)}</strong><small>converted pipeline</small></article><article><span>Conversion</span><strong>{data.summary.conversion}%</strong><small>lead-to-win</small></article></div><article className="panel module-panel"><div className="panel-head"><div><span>Opportunity board</span><h3>Active leads</h3></div></div><Table columns={[{key:'leadNo',label:'Lead'},{key:'business',label:'Business'},{key:'status',label:'Stage'},{key:'source',label:'Source'},{key:'value',label:'Value',render:r=>money(r.value)},{key:'owner',label:'Owner'}]} rows={data.leads}/></article></>}
export default function StrategicModulePage({module}){const{mode}=useAuth();if(module==='crm')return <CRM mode={mode}/>;return null;}
