import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { getApiResource, createApiResource } from '../services/api';
import { demoCrm, demoSchemes } from '../data/strategicData';
const money=(v)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
const Table=({columns,rows})=><div className="table-wrap"><table className="data-table module-table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):String(r[c.key]??'—')}</td>)}</tr>)}</tbody></table></div>;
const Head=({eyebrow,title,text,action,label})=><div className="module-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action&&<button onClick={action}>{label}</button>}</div>;
function CRM({mode}){const[data,setData]=useState(demoCrm);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('crm').then(setData).catch(()=>{})},[mode]);const add=async()=>{try{if(mode==='api')await createApiResource('crm',{action:'lead',name:'Demo Prospect',business:'NCR Demo Electricals',source:'Referral',territory:'Delhi NCR',value:125000});setNotice('Lead created in the sales pipeline.');}catch(e){setNotice(e.message)}};return <><Head eyebrow="Revenue pipeline" title="CRM & sales pipeline" text="Capture prospects, follow-ups, quotation-stage opportunities and won/lost reasons before they become customers." action={add} label="Add demo lead"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Open pipeline</span><strong>{money(data.summary.pipelineValue)}</strong><small>active opportunities</small></article><article><span>Won value</span><strong>{money(data.summary.wonValue)}</strong><small>converted pipeline</small></article><article><span>Conversion</span><strong>{data.summary.conversion}%</strong><small>lead-to-win</small></article></div><article className="panel module-panel"><div className="panel-head"><div><span>Opportunity board</span><h3>Active leads</h3></div></div><Table columns={[{key:'leadNo',label:'Lead'},{key:'business',label:'Business'},{key:'status',label:'Stage'},{key:'source',label:'Source'},{key:'value',label:'Value',render:r=>money(r.value)},{key:'owner',label:'Owner'}]} rows={data.leads}/></article></>}

function Schemes({mode}){const[data,setData]=useState(demoSchemes);const[notice,setNotice]=useState('');useEffect(()=>{if(mode==='api')getApiResource('schemes').then(setData).catch(()=>{})},[mode]);const claim=async()=>{try{if(mode==='api'&&data.schemes[0])await createApiResource('schemes',{action:'submit-claim',schemeId:data.schemes[0].id,eligibleValue:500000});setNotice('Scheme claim calculated and queued with evidence trail.')}catch(e){setNotice(e.message)}};return <><Head eyebrow="Distributor economics" title="Manufacturer schemes & claims" text="Track target slabs, rebates, free-quantity programs and claim settlement without spreadsheet archaeology." action={claim} label="Calculate demo claim"/>{notice&&<div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Active schemes</span><strong>{data.summary.active}</strong><small>current programs</small></article><article><span>Accrued claims</span><strong>{money(data.summary.accrued)}</strong><small>expected manufacturer income</small></article><article><span>Claims</span><strong>{data.summary.claims}</strong><small>tracked settlements</small></article></div><article className="panel module-panel"><Table columns={[{key:'name',label:'Scheme'},{key:'supplier',label:'Manufacturer'},{key:'type',label:'Type'},{key:'target',label:'Target',render:r=>money(r.target)},{key:'rebate',label:'Rebate',render:r=>`${r.rebate}%`},{key:'end',label:'Ends'}]} rows={data.schemes}/></article><article className="panel module-panel"><Table columns={[{key:'claimNo',label:'Claim'},{key:'scheme',label:'Scheme'},{key:'eligible',label:'Eligible',render:r=>money(r.eligible)},{key:'amount',label:'Claim',render:r=>money(r.amount)},{key:'status',label:'Status'}]} rows={data.claims}/></article></>}

export default function StrategicModulePage({module}){const{mode}=useAuth();if(module==='crm')return <CRM mode={mode}/>;if(module==='schemes')return <Schemes mode={mode}/>;return null;}
