import { useEffect, useState } from 'react';
import { createApiResource, getApiResource } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { demoNextgen } from '../data/nextgenData';

const demo = demoNextgen['operations-center'];
export default function SupportCenterPage() {
  const { mode } = useAuth(); const [data, setData] = useState(demo); const [notice, setNotice] = useState('');
  const load = () => { if (mode === 'api') getApiResource('support-center').then(setData).catch((err) => setNotice(err.message)); };
  useEffect(load, [mode]);
  const act = async (action, id) => { try { if (mode === 'api') await createApiResource('support-center', { action, id }); setNotice(action === 'retry-job' ? 'Background job requeued.' : 'Webhook replay queued.'); load(); } catch (err) { setNotice(err.message); } };
  return <div className="support-page"><div className="module-header"><div><span className="section-kicker">Client support operations</span><h1>Support center</h1><p>Give the client one place to inspect API health, failed work, webhook retries, backups, audit activity and offline sync.</p></div><button onClick={load}>Refresh status</button></div>{notice && <div className="inline-notice">{notice}</div>}<div className="report-grid"><article><span>Healthy services</span><strong>{data.summary?.healthy || 0}</strong><small>current checks</small></article><article><span>Degraded</span><strong>{data.summary?.degraded || 0}</strong><small>needs attention</small></article><article><span>Failed jobs</span><strong>{data.summary?.failedJobs || 0}</strong><small>retry queue</small></article><article><span>Webhook retries</span><strong>{data.summary?.failedWebhooks || 0}</strong><small>provider events</small></article></div><div className="support-grid"><article className="panel module-panel"><div className="panel-head"><div><span>Service health</span><h3>Connected systems</h3></div></div><div className="support-services">{(data.services || []).map((row) => <div key={row.id}><span className={row.status === 'Healthy' ? 'support-dot healthy' : 'support-dot'} /><strong>{row.service}</strong><small>{row.message || row.status}</small><em>{row.latency || 0} ms</em></div>)}</div></article><article className="panel module-panel"><div className="panel-head"><div><span>Recovery</span><h3>Backup and sync</h3></div></div><div className="support-recovery"><div><span>Backup</span><strong>{data.backup?.status || 'Not configured'}</strong><small>{data.backup?.lastRun || 'No run reported'}</small></div><div><span>Offline sync</span><strong>{data.offlineSync?.failed || 0} failures</strong><small>{data.offlineSync?.recent || 0} recent receipts</small></div></div></article></div><article className="panel module-panel"><div className="panel-head"><div><span>Action queue</span><h3>Failed jobs and webhook events</h3></div></div><div className="support-actions-list">{(data.jobs || []).filter((row) => row.status === 'Failed').map((row) => <div key={`job-${row.id}`}><span>JOB</span><strong>{row.type}</strong><small>{row.error || 'Retry required'}</small><button onClick={() => act('retry-job', row.id)}>Retry</button></div>)}{(data.webhooks || []).filter((row) => row.status === 'Failed').map((row) => <div key={`hook-${row.id}`}><span>HOOK</span><strong>{row.source} · {row.eventId}</strong><small>{row.error || 'Replay required'}</small><button onClick={() => act('replay-webhook', row.id)}>Replay</button></div>)}{!(data.jobs || []).some((row) => row.status === 'Failed') && !(data.webhooks || []).some((row) => row.status === 'Failed') && <p className="muted">No failed jobs or webhook events.</p>}</div></article></div>;
}
