import { useEffect, useState } from 'react';
import Brand from '../components/Brand';
import { apiBase } from '../services/api';

const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const demo={supplier:'Polycab India Supply',purchaseOrders:[{id:1,poNo:'PO-2026-084',date:'2026-09-20',status:'Partial',total:186400,expected:'2026-09-23'}],submissions:[{id:1,type:'ETA',status:'Submitted',payload:{eta:'2026-09-23',note:'Truck dispatched from Bhiwadi.'},createdAt:'2026-09-21T10:30:00+05:30'}]};

export default function SupplierPortalPage({navigate}){
  const [token,setToken]=useState(localStorage.getItem('setustock_supplier_token')||''); const [data,setData]=useState(token?demo:null); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const load=async(t=token)=>{ if(!t){setData(null);return;} try{const r=await fetch(`${apiBase}/supplier-portal/`,{headers:{Authorization:`Supplier ${t}`}}); if(!r.ok)throw new Error('Supplier session unavailable'); setData(await r.json());}catch{setData(demo);} };
  useEffect(()=>{if(token)load(token)},[]);
  const login=async(e)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const email=f.get('email'); const pin=f.get('pin'); try{const r=await fetch(`${apiBase}/supplier-portal/login/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,pin})}); if(!r.ok)throw new Error('API unavailable'); const x=await r.json(); localStorage.setItem('setustock_supplier_token',x.token); setToken(x.token); await load(x.token);}catch{if(email==='supplier@setustock.demo'&&pin==='1234'){setToken('demo');setData(demo);setError('');}else setError('Use supplier@setustock.demo / 1234 in demo mode.');}};
  const submit=async(type,po)=>{try{if(token!=='demo'){await fetch(`${apiBase}/supplier-portal/`,{method:'POST',headers:{Authorization:`Supplier ${token}`,'Content-Type':'application/json'},body:JSON.stringify({purchaseOrderId:po.id,type,payload:type==='ETA'?{eta:'2026-09-24',note:'Confirmed by supplier'}:{confirmed:true}})});}setNotice(`${type==='ETA'?'ETA update':'PO confirmation'} submitted to buyer.`);}catch(e){setNotice(e.message)}};
  if(!data)return <div className="portal-shell"><header><Brand/><button onClick={()=>navigate('/')}>Back to SetuStock</button></header><main className="portal-login"><section><span className="eyebrow">Supplier collaboration</span><h1>Confirm POs without another email thread.</h1><p>Share delivery dates, invoice references and purchase-order confirmations with your distributor.</p></section><form onSubmit={login}><h2>Supplier sign in</h2>{error&&<div className="form-error">{error}</div>}<label>Email<input name="email" defaultValue="supplier@setustock.demo"/></label><label>PIN<input name="pin" type="password" defaultValue="1234"/></label><button>Sign in</button><small>Demo: supplier@setustock.demo / 1234</small></form></main></div>;
  return <div className="portal-shell"><header><Brand/><div><strong>{data.supplier}</strong> <button onClick={()=>{localStorage.removeItem('setustock_supplier_token');setToken('');setData(null)}}>Sign out</button></div></header><main className="portal-body"><div className="portal-hero"><div><span className="eyebrow">Supplier workspace</span><h1>Purchase orders and delivery commitments</h1><p>Respond directly to the buyer while keeping every update attached to the PO.</p></div></div>{notice&&<div className="inline-notice">{notice}</div>}<article className="panel module-panel"><div className="table-wrap"><table className="data-table module-table"><thead><tr><th>PO</th><th>Date</th><th>Expected</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.purchaseOrders.map(po=><tr key={po.id}><td><strong>{po.poNo}</strong></td><td>{po.date}</td><td>{po.expected||'—'}</td><td>{money(po.total)}</td><td>{po.status}</td><td><button onClick={()=>submit('PO_CONFIRM',po)}>Confirm</button> <button onClick={()=>submit('ETA',po)}>Update ETA</button></td></tr>)}</tbody></table></div></article><article className="panel module-panel"><div className="panel-head"><div><span>Recent responses</span><h3>Submission history</h3></div></div>{data.submissions.map(s=><div className="list-row" key={s.id}><strong>{s.type}</strong><span>{JSON.stringify(s.payload)}</span><small>{s.status}</small></div>)}</article></main></div>;
}
